aave/interface

pages/faucet.page.tsx, src/components/ContentWithTooltip.tsx, src/components/HALTooltip.tsx, src/components/primitives/Link.tsx, src/components/transactions/GasStation/GasStation.tsx, src/components/transactions/Swap/SwapModalContent.tsx, src/layouts/components/DarkModeSwitcher.tsx, src/modules/markets/AssetsListItem.tsx, src/modules/reserve-overview/ApyChart.tsx, src/modules/reserve-overview/ChartLegend.tsx
was causing issues on pnp as these deps are not declared
=> cleanup: remove imports from mui/system

src/modules/reserve-overview/ReserveConfiguration.tsx
closes https://github.com/aave/interface/issues/562
=> fix tooltip

src/components/transactions/Repay/RepayActions.tsx, src/components/transactions/Repay/RepayModalContent.tsx, src/components/transactions/Withdraw/WithdrawModalContent.tsx
fix: repay with -1 in v2 if possible.
fix withdraw max infinite loading.
fix withdraw all when last reserve, when updated happened before modal was updated to success view
=> Fix for v2 repay max. and other fixes

src/components/primitives/BasicModal.tsx, src/components/transactions/Swap/SwapModalContent.tsx
- closes https://github.com/aave/interface/issues/645
- also fixes the scrolling `X` mentioned in https://github.com/aave/interface/issues/644
=> fix: use correct symbol & icon on swap select

cypress/configs/v2-markets/amm-v2-full.config.json, cypress/configs/v2-markets/avalanche-v2-full.config.json, cypress/configs/v2-markets/ethereum-v2-full.config.json, cypress/configs/v2-markets/ethereum-v2-smoke.config.json, cypress/configs/v2-markets/polygon-v2-full.config.json, cypress/configs/v3-markets/arbitrum-v3-full.config.json, cypress/configs/v3-markets/avalanche-v3-full.config.json, cypress/configs/v3-markets/fantom-v3-full.config.json, cypress/configs/v3-markets/polygon-v3-full.config.json, cypress/integration/0-v2-markets/3-avalanche-v2-market/swap.avalanche-v3.spec.ts, cypress/support/steps/main.steps.ts
fix for swap.avalacne-v2.spec.ts with updated naming
=> fix swap avalcnhe spec

src/components/transactions/Repay/RepayModal.tsx, src/components/transactions/Repay/RepayTypeSelector.tsx
- removes a leftover
- cleaner fix for https://github.com/aave/interface/pull/702
=> cleanup: remove leftover

cypress/integration/1-v3-markets/5-fantom-v3-market/0-assets/weth.fantom-v3.spec.ts
FTM price go down, so tests some tests failed by that 
this one is a fix
=> fix weth on ftm

.github/workflows/build-test-deploy.yml, .github/workflows/crowdin-download.yml, .github/workflows/update-cache.yml
Cache and translations updates don't trigger cypress tests anymore
=> ci: skip tests on automated commits

cypress/integration/0-v2-markets/0-main-v2-market/0-assets/bat.aave-v2.spec.ts, cypress/integration/0-v2-markets/0-main-v2-market/0-assets/dai.aave-v2.spec.ts, cypress/integration/0-v2-markets/0-main-v2-market/0-assets/tusd.aave-v2.spec.ts, cypress/integration/0-v2-markets/0-main-v2-market/0-assets/usdc.aave-v2.spec.ts, cypress/integration/0-v2-markets/0-main-v2-market/0-assets/usdt.aave-v2.spec.ts
eth pricing fixing for mainnet tests
=> fixes for eth pricing

package.json, yarn.lock
Bump package version to add fix for Paraswap adpters
=> bump: contract helpers version

.github/workflows/build-test-deploy.yml, .github/workflows/test-deploy-fork.yml, cypress/configs/settings.config.json, cypress/integration/2-settings/change-languages.spec.ts
Covered e2e flow for changing languages.
=> Change language

cypress/integration/2-settings/dark-mode.spec.ts
New UI test for switching from / to Dark mode.
=> e2e test for the dark mode switching

src/components/transactions/Stake/StakeModalContent.tsx
Fixes a bug where staking was not allowed on forks if the base chain allowed staking
=> fix: allow staking on forked chains

src/ui-config/networksConfig.ts
Added Pocket Network HTTPS RPC URLS for:
- Eth Mainnet
- Polygon 
- Avalanche
- Optimism
- Fantom
- Harmony
=> Added Pocket Network

src/ui-config/networksConfig.ts
=> fix: deavtivate compromised rpc

src/components/MarketSwitcher.tsx
=> fix: prevent a market from being un-selected

cypress/integration/1-v3-markets/5-fantom-v3-market/critical-conditions.fantom-v3.spec.ts, cypress/support/commands.ts, cypress/support/steps/verification.steps.ts, package.json, tsconfig.json, yarn.lock
made adaptive verification to reduce flaky results
=> fix for isolated mode test modified verification

cypress/support/tools/tenderly.ts, package.json, yarn.lock
don't understand why this was ever added. Also it's deprecated for 2 years now.
=> deps: remove request

src/ui-config/networksConfig.ts
- Use Alchemy RPC instead of Linkpool for Rinkeby testnet
=> fix: Update to use Alchemy RPC URL for Rinkeby

src/layouts/WalletWidget.tsx, src/ui-config/reservePatches.ts
some weird unnecessary things i stumbled over when doing other stuff
=> fix: remove weird stuff

src/components/transactions/GovDelegation/GovDelegationModalContent.tsx, src/components/transactions/GovVote/GovVoteModalContent.tsx, src/components/transactions/Stake/StakeModalContent.tsx, src/components/transactions/StakeCooldown/StakeCooldownModalContent.tsx, src/components/transactions/StakeRewardClaim/StakeRewardClaimModalContent.tsx, src/components/transactions/UnStake/UnStakeModalContent.tsx, src/utils/marketsAndNetworksConfig.ts
When you are on a fork, the ui will NOT tell you to switch network when mm selects mainnet, which imo is a quite serious issue.
I think introduced here https://github.com/aave/interface/pull/887/files or even present before.
=> fix: fix fork setup

src/components/ContentContainer.tsx
=> fix: break words

.husky/commit-msg, commitlint.config.js, package.json, yarn.lock
- Enforces good, consistent practice for all commits happening on the repo
- Adds in `@commitlint` packages
- Adds in a husky `commit-msg` hook to run commitlint prior to any commit occurring
- Follows the conventional commit format and enforces the standardized rules
- See rules [here](https://github.com/conventional-changelog/commitlint/tree/master/@commitlint/config-conventional)
- Commit will fail and output is generated to console showing issue
=> chore: add in commitlint

cypress/integration/2-settings/stake-abpt.ts, src/modules/staking/GetABPToken.tsx
Added a new e2e test for Staking ABP Token
=> e2e stake-abpt test

.github/workflows/update-cache.yml
The current cache update action doesn't conform to commitlint specs
=> fix: update cache update commit message

cypress/configs/v2-markets/amm-v2-full.config.json, cypress/configs/v2-markets/avalanche-v2-additional.config.json, cypress/configs/v2-markets/avalanche-v2-full.config.json, cypress/configs/v2-markets/ethereum-v2-additional.config.json, cypress/configs/v2-markets/polygon-v2-additional.config.json, cypress/configs/v2-markets/polygon-v2-full.config.json, cypress/configs/v3-markets/arbitrum-v3-additional.config.json, cypress/configs/v3-markets/avalanche-v3-additional.config.json, cypress/configs/v3-markets/avalanche-v3-full.config.json, cypress/configs/v3-markets/fantom-v3-additional.config.json, cypress/configs/v3-markets/fantom-v3-full.config.json, cypress/configs/v3-markets/optimism-v3-additional.config.json, cypress/configs/v3-markets/polygon-v3-additional.config.json, cypress/configs/v3-markets/polygon-v3-full.config.json, cypress/integration/0-v2-markets/0-main-v2-market/critical-conditions.aave-v2.spec.ts, cypress/integration/0-v2-markets/1-amm-v2-market/critical-conditions.amm-v2.spec.ts, cypress/integration/0-v2-markets/2-polygon-v2-market/critical-conditions.polygon-v2.spec.ts, cypress/integration/0-v2-markets/3-avalanche-v2-market/critical-conditions.avalanche-v2.spec.ts, cypress/integration/1-v3-markets/2-avalanche-v3-market/critical-conditions.avalanche-v3.spec.ts, cypress/integration/1-v3-markets/3-polygon-v3-market/critical-conditions.polygon-v3.spec.ts, cypress/integration/1-v3-markets/4-optimism-v3-market/0-assets/susd.optimism-v3.spec.ts, cypress/integration/1-v3-markets/4-optimism-v3-market/critical-conditions.optimism-v3.spec.ts, cypress/integration/1-v3-markets/5-fantom-v3-market/critical-conditions.fantom-v3.spec.ts, cypress/support/steps/main.steps.ts, cypress/support/steps/verification.steps.ts
improve stability of critical conditions tests
=> improve critical conditions test

src/components/transactions/Emode/EmodeModalContent.tsx, src/components/transactions/Emode/EmodeNaming.ts, src/components/transactions/Emode/EmodeSelect.tsx, src/hooks/app-data-provider/useAppDataProvider.tsx, src/modules/dashboard/DashboardEModeButton.tsx, src/modules/dashboard/lists/BorrowedPositionsList/BorrowedPositionsList.tsx, src/modules/reserve-overview/ReserveActions.tsx, src/modules/reserve-overview/ReserveConfiguration.tsx
Soon there will be a new eMode added and the current id - name mapping doesn't scale very well as these groups could vary from market to market or network to network.
This pr uses the native eModeLabels
=> fix: use non hardcoded labels as it doesn't scale

cypress.config.ts, cypress/README.md, cypress/configs/settings.config.ts, cypress/configs/v2-markets/amm-v2-full.config.ts, cypress/configs/v2-markets/amm-v2-smoke.config.ts, cypress/configs/v2-markets/avalanche-v2-full.config.ts, cypress/configs/v2-markets/ethereum-v2-additional.config.ts, cypress/configs/v2-markets/ethereum-v2-full.config.ts, cypress/configs/v2-markets/ethereum-v2-smoke.config.ts, cypress/configs/v2-markets/polygon-v2-additional.config.ts, cypress/configs/v2-markets/polygon-v2-full.config.ts, cypress/configs/v2-markets/polygon-v2-smoke.config.ts, cypress/configs/v3-markets/arbitrum-v3-additional.config.ts, cypress/configs/v3-markets/arbitrum-v3-full.config.ts, cypress/configs/v3-markets/arbitrum-v3-smoke.config.ts, cypress/configs/v3-markets/avalanche-v3-additional.config.ts, cypress/configs/v3-markets/avalanche-v3-full.config.ts, cypress/configs/v3-markets/avalanche-v3-smoke.config.ts, cypress/configs/v3-markets/fantom-v3-additional.config.ts, cypress/configs/v3-markets/fantom-v3-full.config.ts, cypress/configs/v3-markets/fantom-v3-smoke.config.ts, cypress/configs/v3-markets/optimism-v3-additional.config.ts, cypress/configs/v3-markets/optimism-v3-full.config.ts, cypress/configs/v3-markets/optimism-v3-smoke.config.ts, cypress/configs/v3-markets/polygon-v3-additional.config.ts, cypress/configs/v3-markets/polygon-v3-full.config.ts, cypress/configs/v3-markets/polygon-v3-smoke.config.ts, cypress/fixtures/constans.json
Run prettier on cypress files. Only formatting changes, nothing else.
=> chore: run prettier on cypress files

package.json
- Fixes a bug with lint staged from running lint on `.filename` files, like `.prettierignore` and `.eslintcache`, etc.
=> fix: lint-staged

.github/pull_request_template.md
- Adds a new Reviewer Checklist item for QA
=> chore: add QA verification checklist item for reviews

src/modules/dashboard/lists/SuppliedPositionsList/SuppliedPositionsListMobileItem.tsx
- Fixes a bug where the swap modal wasn't opening on small screens
closes #1180
=> fix(swap-modal): open swap modal on mobile

.github/pull_request_template.md
=> chore: update PR checklists

.github/actions/private-ipfs-pin/action.yml, .github/workflows/update-prod-staging.yml
- Make IPFS pin failures more visible
---
=> ci: make pin failures more visible

.github/actions/fork-result-label/action.yml, src/hooks/useReservesHistory.tsx
- Fixes an issue where the graphs wouldn't load properly on page load
closes #1239 
Also ran prettier on a new file that was added
---
=> fix: graph initial load error

src/components/transactions/ClaimRewards/ClaimRewardsModalContent.tsx, src/modules/dashboard/DashboardTopPanel.tsx
The AMM market shares an incentives controller with V2 mainnet market, so rewards will be visible/claimable across both markets, however, the condition to fetch stkAave price was not applied to AMM market so it was defaulting to the incentives price feed which was incorrect.
This switches the AMM market to use the AAVE reserve price (same as V2 mainnet), but since the token doesn't exist on the AMM market the end result is a price of 0 and just hiding incentives on this market.
TL;DR AMM market incentives hidden
---
Please ensure you, as the reviewer(s), have gone through this checklist to ensure that the code changes are ready to …
=> fix: amm market incentives display

package.json, src/components/transactions/Faucet/FaucetModalContent.tsx, yarn.lock
- Bump to latest version
- Add support for faucet change
---
=> chore: bump utils

pages/governance/proposal/[proposalId].governance.tsx, src/components/primitives/FormattedNumber.tsx, src/modules/governance/VoteBar.tsx, src/modules/governance/proposal/VotersListItem.tsx
- Adds optional roundDown parameter to FormattedNumber primitive
- Applies roundDown to values in governance page
- Adds 2 decimal places to vote values over 1M and 1 decimal for value over 100k in VoteList to avoid large loss of precision (i.e. 1_999_999_999 now displays as 1.99M instead of 1M)
Note: this last change still maintains the width for all vote values so there shouldn't be any design concerns here ^
=> feat: round down formatting

src/components/WalletConnection/WalletSelector.tsx
- Updates wallet selector for Coinbase Wallet from `Coinbase` -> `Coinbase Wallet` for accurate branding.
`Coinbase` refers to the blue retail app used for buying/selling/trading crypto.
`Coinbase Wallet` is the self-custody wallet product, separate from the exchange product.
---
- []  The `Ready for Dev Review` label has been added
- []  End-to-end tests are passing without any errors
- []  Code style generally follows existing patterns
- []  Code …
=> fix: CBW wallet selector naming

pages/markets.page.tsx, src/locales/en/messages.po, src/modules/markets/MarketAssetListTitle.tsx, src/modules/markets/MarketAssetSearchInput.tsx, src/modules/markets/MarketAssetsList.tsx, src/modules/markets/MarketAssetsListItem.tsx, src/modules/markets/MarketAssetsListItemLoader.tsx, src/modules/markets/MarketAssetsListMobileItem.tsx, src/modules/markets/MarketAssetsListMobileItemLoader.tsx
- Renames all components used under `/markets` to use a prefix of `Market`
This helps alleviate minor confusion when working amongst the codebase but also properly keeps things named for their scope.
---
=> chore: prefix market components with 'Market'

CONTRIBUTING.md
=> Fix: typos

pages/governance/proposal/[proposalId].governance.tsx
Fixes: http://app.aave.com/governance/proposal/?proposalId=125
---
=> fix: governance images

src/modules/markets/MarketAssetsListItem.tsx
- Fixes typo introduced into borrowing disabled design update PR
---
=> fix: markets total borrowed value

cypress/e2e/0-v2-markets/0-main-v2-market/0-assets/mana.aave-v2.cy.ts, cypress/e2e/0-v2-markets/0-main-v2-market/0-assets/mkr.aave-v2.cy.ts, src/modules/markets/MarketAssetsListMobileItem.tsx
- Fix disabled mobile on all reserves 
---
=> fix: disabled mobile issue

src/components/infoTooltips/FrozenTooltip.tsx, src/modules/dashboard/lists/BorrowedPositionsList/BorrowedPositionsListMobileItem.tsx, src/modules/dashboard/lists/ListItemWrapper.tsx, src/modules/dashboard/lists/ListMobileItemWrapper.tsx, src/utils/marketsAndNetworksConfig.ts
If an asset is frozen and has borrow disabled flag the warning icons are duplicated.
This PR overrides the borrow disabled icon if an asset is also frozen. Can test with this address: 0xa7888f85bd76deef3bd03d4dbcf57765a49883b3
---
=> fix: duplicated warning icons if asset is frozen and has borrow disabled flag

src/hooks/useCryptoBuyAvailable.tsx, src/modules/reserve-overview/ReserveActions.tsx
- Show correct wallet balance when toggling between wrapped base assets
- Use correct asset when opening supply modal
- Don't show 'Buy with fiat' button if the asset is not supported
---
=> fix: issues with wrapped base assets

src/layouts/AppHeader.tsx, src/uiConfig.ts
=> chore: revert logo

cypress/e2e/1-v3-markets/3-polygon-v3-market/isolated-and-emode.polygon-v3.cy.ts
Fixing e2e on the polygon V3 
---
=> Fixing e2e tests on polygonV3

src/modules/governance/VotingPowerInfoPanel.tsx
- fixes delegate issue described as follows: 
When an user of Aave interface, delegates all his voting and proposition power, the delegation option is greyed out. So he can't revoke the delegation back to himself through the UI.
- …
---
=> fix: allow to delegate if already delegating

cypress/e2e/0-v2-markets/0-main-v2-market/stake.aave-v2.cy.ts, package.json, src/components/transactions/Stake/StakeActions.tsx, yarn.lock
- Re-adds approval param to `StakingActions` removed in migration PR
---
=> fix: staking approval

package.json, yarn.lock
- utils package version bump, see https://github.com/aave/aave-utilities/pull/505
---
=> chore: utils bump for hf fix [skip cypress]

package.json, src/components/transactions/CollateralChange/CollateralChangeModalContent.tsx, src/components/transactions/RateSwitch/RateSwitchModalContent.tsx, src/components/transactions/Swap/SwapModalContent.tsx, src/components/transactions/Swap/SwapModalDetails.tsx, src/components/transactions/Withdraw/WithdrawModalContent.tsx, src/modules/dashboard/lists/SuppliedPositionsList/SuppliedPositionsListItem.tsx, src/modules/dashboard/lists/SuppliedPositionsList/SuppliedPositionsListMobileItem.tsx, src/modules/dashboard/lists/SupplyAssetsList/SupplyAssetsList.tsx, src/modules/migration/MigrationListItem.tsx, src/modules/migration/MigrationListMobileItem.tsx, src/modules/reserve-overview/SupplyInfo.tsx, src/store/v3MigrationSelectors.ts, src/utils/hfUtils.ts, yarn.lock
- Replace all instances of checking a reserve's usage as collateral based on `reserve.usageAsCollateralEnabled` with `reserve.reserveLiquidationThreshold !== '0'` 
The usage as collateral enabled flag is based on LTV, but this doesn't handle a case where LTV is set to 0 for an asset actively being used as collateral.
---
=> fix: collateral checks

src/ui-config/marketsConfig.tsx
- Enable rate history charts for all V3 Ethereum market
---
=> feat: enable v3 mainnet charts

.prettierignore, src/store/v3MigrationSelectors.ts
- Fixes a bug where the approval/permit payloads were not generated correctly for stable debt assets. The previous logic assumed that if there was a stable debt asset, there would be a corresponding variable debt asset, and the total amount would be the sum. Now, all debt assets will get an approval payload generated, with the debt token address always being set to the variable debt token since all migrated debt becomes variable.
- Also added `scripts/` to prettier ignore since there kept being formatting changes on the cache file
---
Please ensure you, as the reviewer(s), have gone through this checklist to ensure that the code …
=> fix: stable debt migration

src/ui-config/networksConfig.ts
- Adds back in pokt rpc for eth mainnet
---
=> fix: use pokt rpc

src/components/transactions/Repay/CollateralRepayModalContent.tsx, src/components/transactions/Swap/SwapModalContent.tsx
Fixes several issues with price impact calculation in collateral swap and repay with collateral modals.
Example: Polygon V3 Collateral Swap
New:
Previous version shows -0.12% which is incorrect according to `((V2 - V1) / V1) * 100`
3 total changes to price impact:
- Shift decimals 2 places
- Use  `((V2 - V1) / V1) * 100` which flips input and output values compared to previous version and gives correct percent change
- Handle output amount from repay all case for repay with collateral
---
Please ensure you, as the reviewer(s), have gone through this checklist to ensure that the code changes are ready to ship safely and to help …
=> fix: price impact calculations

src/components/caps/CapsCircularStatus.tsx
=> fix: supply cap pie chart overflow

cypress/README.md, cypress/e2e/3-stake-governance/governance-deligation.cy.ts, cypress/support/steps/configuration.steps.ts, cypress/support/steps/governance.steps.ts, cypress/support/tools/tenderly.ts, src/components/transactions/GovDelegation/DelegationTokenSelector.tsx, src/hooks/app-data-provider/useAppDataProvider.tsx
=> fix: e2e tests

src/layouts/TopBarNotify.tsx
-Updates the colors on the notify banner to a linear gradient
---
=> chore: update banner colors

src/modules/dashboard/lists/BorrowedPositionsList/BorrowedPositionsList.tsx, src/modules/dashboard/lists/BorrowedPositionsList/BorrowedPositionsListMobileItem.tsx
- Fixes a bug where the mobile view for borrowed positions didn't differentiate between stable and variable debt values
---
=> fix: handle stable and variable debt values in borrow list item

pages/_document.page.tsx, public/manifest.json
- Updated app name
- Updated theme color
---
=> fix: update theme color and app name

src/utils/getMaxAmountAvailableToSupply.ts
- Removes debtCeiling check from maxAvailableToSupply since it is applied incorrectly. debtCeiling is a limit on the amount to *borrow* using an asset as collateral so this should not limit the amount to supply
---
=> fix: deleted condition check in supply for isolated reserves

cypress/e2e/0-v2-markets/2-polygon-v2-market/0-assets/dai.polygon-v2.cy.ts, cypress/e2e/0-v2-markets/2-polygon-v2-market/0-assets/matic.polygon-v2.cy.ts, cypress/e2e/0-v2-markets/2-polygon-v2-market/0-assets/usdc.polygon-v2.cy.ts, cypress/e2e/0-v2-markets/2-polygon-v2-market/0-assets/usdt.polygon-v2.cy.ts, cypress/e2e/0-v2-markets/2-polygon-v2-market/0-assets/wbtc.polygon-v2.cy.ts, cypress/e2e/0-v2-markets/2-polygon-v2-market/0-assets/weth.polygon-v2.cy.ts, cypress/e2e/0-v2-markets/2-polygon-v2-market/critical-conditions.polygon-v2.cy.ts, cypress/e2e/0-v2-markets/2-polygon-v2-market/swap.polygon-v2.cy.ts
=> fix: switch off tests for polygon v2

src/modules/reserve-overview/ReserveTopDetails.tsx
Fixes #1605 
replaced general img tag with TokenIcon component in reserves page
---
=> fix: token icon in reserves page

src/layouts/AppHeader.tsx, src/layouts/TopBarNotify.tsx, src/store/layoutSlice.ts
fixes #1611 
Added WalletWigit to layout store on mobile
The TopBarNotify component now considers both MobileMenu and WalletWidget on mobile. Functions for each menu were created to update the layout store accordingly, improving clarity. The store's state encompasses both menus, avoiding confusion. This ensures accurate layout representation.
Screen Capture
<table>
<tr>
<th> Before </th>
<th> After </th>
</tr>
<tr>
<td>
https://github.com/aave/interface/assets/89173284/ef4c004f-d23d-404f-ae4a-3117747f267f
</td>
<td>
https://github.com/aave/interface/assets/89173284/f4ee6c90-769d-4dba-92ab-7978ecf5ec79
</td>
</tr>
</table>
---
Please …
=> fix: Warning bar in wallet menu on mobile

src/store/v3MigrationSelectors.ts, src/store/v3MigrationSlice.ts
- Fix issue with being unable to migrate borrow position from V2 -> V3 using credit delegation signature
Initially this buffer was added in the UI, but it was moved to utilities to fix #1539. Credit delegation signature payloads are handled exclusively on the UI, so the buffer needs to be applied separately.
The reason a parameter is added is because this same selector function is used for `migrateWithPermits`, so the buffer flag is not set when used here.
---
Please ensure you, as the reviewer(s), have gone through this checklist to ensure that the code changes are ready to ship safely and to help mitigate any downstream issues …
=> fix: migration with credit delegation signature

.github/actions/private-ipfs-pin/action.yml
removing expiration of pins after 144h on private ipfs cluster
=> CI: Removed expiration time for pinned files in our private IPFS

pages/governance/index.governance.tsx
- Set short description to empty string if it's missing from the proposal
---
=> fix: handle short description missing [skip cypress]

src/ui-config/reservePatches.ts
- Circle is bringing USDC natively to Arbitrum, so to avoid confusion it is requested to change the name of the existing bridged USDC token for clarity, [more info](https://twitter.com/arbitrum/status/1664255653152542720?s=20)
- Updates name to "Bridged USDC" and symbol to "USDC.e" for token 0xff970a61a04b1ca14834a43f5de4533ebddb5cc8 in `reservePatches`
---
=> chore: Arbitrum bridged usdc reserve patch

.github/actions/build/action.yml
=> chore: fix config [skip cypress]

.github/workflows/build-test-deploy.yml, src/layouts/MainLayout.tsx
=> chore: remove debug and fix env 

next.config.js, src/store/analyticsSlice.ts
=> fix: rewrites [skip cypress]

src/modules/governance/ProposalListItem.tsx, src/modules/governance/ProposalsList.tsx, src/modules/governance/utils/formatProposal.ts, src/ui-config/governanceConfig.ts
- Consolidate governance addresses into `governanceConfig`
- Use the address book for all the addresses that are available
It'd probably make sense to restructure/rename the governance config props, but I just left it as is for now to limit the amount of changes for this PR.
---
=> fix: governance config

src/components/TransactionEventHandler.tsx
=> feat: add additional tx param hash

src/components/TextWithTooltip.tsx, src/components/lists/ListWrapper.tsx, src/modules/dashboard/lists/BorrowedPositionsList/BorrowedPositionsList.tsx, src/modules/dashboard/lists/SuppliedPositionsList/SuppliedPositionsList.tsx
Fixes #1207 
I change it so that when the tooltip opens the content is not scrollable once the tooltip is closed the content becomes scrollable again.
<table style="margin-left: auto; margin-right: auto;">
<tr>
<th >Before<th>
<th>After <th>
<tr> 
<tr>
<td> 
<video alt="Screen Recording" src="https://github.com/aave/interface/assets/89173284/7ca96b2c-4988-42a5-a697-b9be2f59f62d
" />
<td>
<td>
<video alt="Screen Recording" src="https://github.com/aave/interface/assets/89173284/a1bc2019-7ffc-4cb8-8a91-8be352a40a0f
" />
<td>
<tr>
<table>
---
Please ensure you, as the reviewer(s), have gone through this checklist to ensure that the code …
=> fix: moving assets breaks interface

src/components/MarketSwitcher.tsx
=> chore: use updated gradient

package.json, src/components/transactions/Stake/StakeActions.tsx, src/helpers/useTransactionHandler.tsx, src/store/stakeSlice.ts, yarn.lock
- feat/gho PR enables `stakeWithPermit`. Final utilities update changes the location of the function call from StakeUIHelper to StakedTokenV3 directly, allowing `deadline` to be passed an extra parameter
---
=> chore: staking with permit source

cypress/e2e/0-v2-markets/0-main-v2-market/0-assets/tusd.aave-v2.cy.ts, cypress/e2e/1-v3-markets/4-optimism-v3-market/e-mode.optimism-v3.cy.ts, src/components/transactions/Borrow/BorrowModal.tsx, src/components/transactions/Repay/RepayModalContent.tsx, src/hooks/app-data-provider/useAppDataProvider.tsx, src/hooks/useReserveActionState.tsx, src/modules/dashboard/lists/BorrowAssetsList/BorrowAssetsList.tsx, src/modules/dashboard/lists/BorrowedPositionsList/BorrowedPositionsList.tsx, src/modules/dashboard/lists/SupplyAssetsList/SupplyAssetsList.tsx, src/modules/markets/MarketAssetsListContainer.tsx, src/modules/reserve-overview/ReserveActions.tsx, src/modules/reserve-overview/ReserveConfigurationWrapper.tsx, src/modules/reserve-overview/ReserveTopDetailsWrapper.tsx, src/store/ghoSlice.ts, src/ui-config/marketsConfig.tsx, src/utils/ghoUtilities.tsx
- Create version which dynamically checks for GHO reserve initialized on Pool to decide rendering of GHO display elements
- Replaces all instances of `isGhoAndSupported` util function with `displayGho` store import
- `displayGho` depends on `isGhoLive`, which updates on `refreshGhoData` based on whether Pool reserves list contains GHO address
---
=> chore: mainnet prep

LICENSE.md, README.md, package.json
=> chore: update package json

src/components/transactions/Borrow/GhoBorrowSuccessView.tsx
=> feat: dynamic loading component

src/components/transactions/Borrow/GhoBorrowSuccessView.tsx
=> fix: add skeleton loader for success image

src/components/transactions/Borrow/GhoBorrowModalContent.tsx, src/hooks/app-data-provider/useAppDataProvider.tsx, src/modules/dashboard/lists/BorrowAssetsList/GhoBorrowAssetsListItem.tsx, src/modules/dashboard/lists/BorrowedPositionsList/GhoBorrowedPositionsListItem.tsx, src/utils/__tests__/ghoUtilities.spec.ts, src/utils/ghoUtilities.tsx
-Borrowing max facilitator capacity gives an error caused by small decimal imprecision, this adds a buffer to max availableBorrows
---
=> chore: facilitator cap margin

src/components/transactions/Borrow/GhoBorrowSuccessView.tsx
=> Feat: gho success image square borders

pages/staking.staking.tsx, src/modules/markets/MarketAssetsListContainer.tsx, src/store/ghoSlice.ts
- Flag was added to ghoSlice to check whether reserve is live prior to proposal being executed, this removes the check in all places
---
=> chore: remove check for GHO reserve

src/components/transactions/Repay/RepayModalContent.tsx, src/utils/hfUtils.ts
Fixed health factor bug where it showed bellow zero values
- closes #1104 bug
None
---
=> fix: :bug: 1104 health factor

src/hooks/app-data-provider/useAppDataProvider.tsx
=> fix: limit formatUserSummaryWithDiscount

src/ui-config/networksConfig.ts
=> chore: add another rpc on sepolia

cypress/e2e/4-gho-ethereum/gho-basic.ethereum-v3.cy.ts, src/modules/dashboard/lists/BorrowedPositionsList/BorrowedPositionsListItem.tsx, src/modules/dashboard/lists/BorrowedPositionsList/BorrowedPositionsListMobileItem.tsx
- Fixes disabled debt switch out of frozen reserves
---
=> chore: fix debt switch disabled on frozen reserves

src/modules/markets/MarketAssetsListItem.tsx, src/modules/markets/MarketAssetsListMobileItem.tsx
=> fix: stable rates on market page

src/components/transactions/Swap/SwapModalContent.tsx
- Removes GHO from list of collateral swap targets since it cannot be supplied
---
=> fix: don't show gho in collateral swap targets

cypress/e2e/0-v2-markets/0-main-v2-market/swap.aave-v2.cy.ts, cypress/e2e/0-v2-markets/0-main-v2-market/switch.aave-v2.cy.ts, cypress/e2e/1-v3-markets/2-avalanche-v3-market/swap.avalanche-v3.cy.ts, cypress/e2e/1-v3-markets/3-polygon-v3-market/swap.polygon-v3.cy.ts, cypress/e2e/1-v3-markets/3-polygon-v3-market/switch.polygon-v3.cy.ts, src/modules/markets/MarketAssetsListContainer.tsx, src/store/poolSelectors.ts
=> feat: markets sort by tvl

package.json, src/hooks/paraswap/common.ts, yarn.lock
=> fix: paraswap fee redirection

src/modules/dashboard/lists/BorrowAssetsList/BorrowAssetsList.tsx
switched reserves.length check for borrowDisabled
closes [#1671](https://github.com/aave/interface/issues/1671)
- Fixes 1671 bug
- Adds 0 feature
None
---
- []  There are no CI changes, or they have been approved by the DevOps and Engineering team(s)
=> fix: :bug: fix bug 1671

src/components/transactions/DebtSwitch/DebtSwitchModalContent.tsx
- Fixes a bug where the wrong amount was being checked for available liquidity on debt switch. Input amount refers to the amount of the target asset received in this case.
---
=> fix: liquidity check for debt switch

cypress/e2e/4-gho-ethereum/gho-basic.ethereum-v3.cy.ts, cypress/e2e/4-gho-ethereum/gho-modal.gho-v3.cy.ts, src/modules/dashboard/lists/BorrowedPositionsList/BorrowedPositionsListItem.tsx, src/modules/dashboard/lists/BorrowedPositionsList/GhoBorrowedPositionsListItem.tsx
- Disables actions for paused reserves
---
=> fix: handle paused reserves

.github/workflows/build-test-deploy.yml, .github/workflows/test-deploy-fork.yml, cypress/configs/v3-markets/base-v3-smoke.config.ts, cypress/e2e/0-v2-markets/0-main-v2-market/0-assets/dai.aave-v2.cy.ts, cypress/e2e/1-v3-markets/6-base-v3-market/0-assets/usdbc.base-v3.cy.ts, cypress/e2e/1-v3-markets/6-base-v3-market/0-assets/weth.base-v3.cy.ts, cypress/fixtures/assets.json, cypress/support/steps/configuration.steps.ts
- coverage for base market
---
=> feat: test coverage for base market

src/components/transactions/Withdraw/WithdrawAndSwitchActions.tsx
- Don't ask for approval if already unlimited
- Don't show approval type if no amount entered
---
=> fix: initial modal states

pages/reserve-overview.page.tsx
=> chore: fix reserve page bug

src/components/transactions/Borrow/GhoBorrowModalContent.tsx, src/hooks/app-data-provider/useAppDataProvider.tsx, src/modules/dashboard/lists/BorrowAssetsList/GhoBorrowAssetsListItem.tsx, src/modules/dashboard/lists/BorrowAssetsList/types.ts, src/modules/dashboard/lists/BorrowedPositionsList/GhoBorrowedPositionsListItem.tsx, src/modules/reserve-overview/Gho/GhoBorrowInfo.tsx, src/modules/reserve-overview/ReserveActions.tsx, src/utils/getMaxAmountAvailableToBorrow.ts
- Interface previously assumed the borrow cap was the facilitator level. A recent proposal set the GHO borrow cap, so theses changes take that value into account to calculate the maximum amount that is available to mint.
---
=> fix: gho borrow cap and facilitator level checks [skip cypress]

src/modules/dashboard/lists/BorrowedPositionsList/BorrowedPositionsListItem.tsx, src/modules/dashboard/lists/BorrowedPositionsList/GhoBorrowedPositionsListItem.tsx, src/modules/dashboard/lists/SuppliedPositionsList/SuppliedPositionsListItem.tsx, src/modules/dashboard/lists/SuppliedPositionsList/SuppliedPositionsListMobileItem.tsx
- Updates the color states across withdraw, borrow, switch 
---
=> feat: rework button active states

cypress/e2e/1-v3-markets/0-ethereum-v3-market/0-assets/dai.ethereum-v3.cy.ts, cypress/e2e/1-v3-markets/1-arbitrum-v3-market/0-assets/dai.arbitrum-v3.cy.ts, cypress/e2e/1-v3-markets/2-avalanche-v3-market/0-assets/dai.avalanche-v3.cy.ts, cypress/e2e/1-v3-markets/3-polygon-v3-market/0-assets/dai.polygon-v3.cy.ts, cypress/e2e/1-v3-markets/4-optimism-v3-market/0-assets/dai.optimism-v3.cy.ts, cypress/support/steps/main.steps.ts
- withdraw and switch functionality for all v3 markets (excpet base and fantom)
---
=> feat: test coverage for withdraw and switch functionality

pages/500.page.tsx, src/layouts/AppFooter.tsx
=> chore: update discord [skip cypress]

src/ui-config/networksConfig.ts
There have been two reported instances where this particular RPC returns gas estimation error, but the txn succeeds when simulating.
---
=> chore: remove rpc which unreliably fails gas estimation

package.json, src/ui-config/marketsConfig.tsx, yarn.lock
- Bumps address book package version
---
=> chore: bump address book version

cypress/e2e/3-stake-governance/stake.cy.ts, cypress/e2e/4-gho-ethereum/gho-discount-dashboard.gho-v3.cy.ts, cypress/support/steps/stake.steps.ts, src/modules/staking/StakingPanel.tsx
- turn on stake page
- refactor tests added switch approve type 
- add restake and claim tests
---
=> feat: refactor and enable stake tests for aave and abpt

.github/workflows/build-test-deploy-dev.yml, .github/workflows/test-deploy-fork.yml, .github/workflows/update-prod-staging.yml
Fixing Pinata check and removing old test left
in dev workflow
=> Fixing Pinata check and removing old test

src/modules/dashboard/lists/ListItemCanBeCollateral.tsx
- Fixes bug showing (i) twice on the supplied asset list
- …
---
=> fix: showing badge twice

pages/_app.page.tsx, src/components/transactions/Switch/SwitchModal.tsx, src/components/transactions/Switch/SwitchModalContent.tsx, src/components/transactions/Switch/SwitchTxSuccessView.tsx
- success modal icons
- lazy load modal
=> fix: icons

src/components/TransactionEventHandler.tsx, src/components/transactions/Switch/SwitchActions.tsx
=> feat: added chainId to actions

package.json, src/components/transactions/Switch/SwitchActions.tsx, src/components/transactions/Switch/SwitchModalContent.tsx, src/hooks/paraswap/common.ts, src/hooks/paraswap/useParaswapRates.ts, yarn.lock
=> Feat: Paraswap partner switch

cypress/e2e/4-gho-ethereum/fixtures/gho.json, src/helpers/useTransactionHandler.tsx
- Don't set tx error if not mounted
---
=> fix: tx errors

cypress/e2e/5-widgets/switch-tool.cy.ts, src/modules/dashboard/lists/BorrowAssetsList/BorrowAssetsListItem.tsx, src/modules/dashboard/lists/SupplyAssetsList/SupplyAssetsListItem.tsx
- Default shows USD balances on assets to supply in each row
---
=> chore: show usd values on assets for supply

src/layouts/AppFooter.tsx
- Updates link to Aave twitter account
=> fix: link to updated twitter acount

src/layouts/MainLayout.tsx
=> chore: update banner [skip cypress]

README.md
=> fix: readme [skip cypress]

src/modules/dashboard/lists/SuppliedPositionsList/SuppliedPositionsListItem.tsx, src/modules/dashboard/lists/SuppliedPositionsList/SuppliedPositionsListMobileItem.tsx, src/modules/dashboard/lists/SupplyAssetsList/SupplyAssetsListItem.tsx, src/modules/dashboard/lists/SupplyAssetsList/SupplyAssetsListMobileItem.tsx
- Updates actions based on paused status
---
=> fix: disable actions when reserve is paused [skip cypress]

src/layouts/MainLayout.tsx
=> chore: update banner text [skip cypress]

LICENSE.md, README.md
=> chore: update license

src/ui-config/networksConfig.ts
- Adds in pokt rpc for Arbitrum
---
=> feat: add arb pokt rpc

src/ui-config/networksConfig.ts
- Adds rate history url for Base and Metis markets
---
=> feat: rates history for base and metis

src/layouts/MainLayout.tsx
- removes notification messages
---
=> chore: remove notify messages [skip cypress]

src/modules/dashboard/lists/BorrowAssetsList/GhoBorrowAssetsListItem.tsx
=> feat: align gho borrow list item

src/modules/governance/utils/formatProposal.ts
- Fixes timestamp fetching block number with provider 
---
=> fix: bug on governance

.github/workflows/test-deploy-fork.yml, .github/workflows/update-prod-staging.yml
=> remove ipfs servers from fork

package.json, src/components/WalletConnection/WalletSelector.tsx, src/libs/web3-data-provider/WalletConnectConnector.ts, src/libs/web3-data-provider/WalletOptions.ts, src/libs/web3-data-provider/Web3Provider.tsx, yarn.lock
=> chore: package

.github/actions/dev-ipfs-pin/action.yml, .github/actions/production-ipfs-pin/action.yml, .github/workflows/update-prod-staging.yml
We are removing crust action, and adding 20s of timeout for ipfs to pin the content in the cluster
- Removes crust action
- Increase 20s timeout period
- …
We are removing crust action, and adding 20s of timeout for ipfs to pin the content in the cluster
=> ipfs: remove crust and increase timeout time

src/ui-config/governanceConfig.ts
=> fix: gov main [skip cypress]

src/ui-config/permitConfig.ts
=> feat: disable aave permit

pages/governance/proposal/v3/[proposalId].governance.tsx, src/components/primitives/Link.tsx
=> feat: New route for governance v3 proposals

src/hooks/governance/useProposal.ts, src/hooks/governance/useProposals.ts, src/modules/governance/utils/formatProposal.ts, src/services/GovernanceV3Service.ts, src/ui-config/governanceConfig.ts
- Updated config for payload controllers
- Updated subgraph url
- fetch/parse proposal from ipfs 
---
=> fix: payload controllers and subgraph url

pages/governance/proposal/[proposalId].governance.tsx, src/components/primitives/Link.tsx
=> feat: old proposal route

src/hooks/governance/useProposal.ts, src/ui-config/governanceConfig.ts
- Handles the proposal id of 0 case properly
- Adds in missing payload controller config for Metis
---
=> fix: proposal data fetching

src/modules/governance/ProposalV3ListItem.tsx
=> fix: remove network icon on list

pages/governance/v3/proposal/index.governance.tsx, src/components/primitives/Link.tsx
=> feat: Dynamic link for proposals

cypress/e2e/0-v2-markets/3-avalanche-v2-market/0-assets/wbtc.avalanche-v2.cy.ts
=> fix: hotfix for wbtc avalanche v2 tests

cypress/e2e/0-v2-markets/3-avalanche-v2-market/0-assets/wbtc.avalanche-v2.cy.ts, src/ui-config/networksConfig.ts
- Updates POKT rpcs as they are deprecated and moving to grove 
---
=> feat: update pokt to grove

src/ui-config/marketsConfig.tsx
=> chore: market name [skip cypress]

src/components/transactions/Warnings/MarketWarning.tsx, src/utils/marketsAndNetworksConfig.ts
- fix links to gov v2 proposals
=> fix: gov v2 proposal links

src/ui-config/marketsConfig.tsx
- Enables switch features on bnb
=> feat: enable switch features on bnb

pages/staking.staking.tsx, src/components/transactions/Stake/StakeModalContent.tsx, src/components/transactions/StakeCooldown/StakeCooldownModalContent.tsx, src/components/transactions/StakeRewardClaim/StakeRewardClaimModalContent.tsx, src/components/transactions/StakeRewardClaimRestake/StakeRewardClaimRestakeModalContent.tsx, src/components/transactions/UnStake/UnStakeModalContent.tsx, src/hooks/stake/common.ts, src/hooks/stake/useGeneralStakeUiData.ts, src/hooks/stake/useUserStakeUiData.ts, src/hooks/useModal.tsx, src/modules/staking/StakingPanelNoWallet.tsx, src/ui-config/stakeConfig.ts
- Always query for all stake tokens
- Allow an optional param to select a stake token from the query
=> fix: stake query cache

src/components/transactions/Stake/StakeModalContent.tsx, src/components/transactions/StakeRewardClaim/StakeRewardClaimModalContent.tsx, src/components/transactions/StakeRewardClaimRestake/StakeRewardClaimRestakeModalContent.tsx, src/components/transactions/UnStake/UnStakeModalContent.tsx
- Fixes normalizing token prices in USD
=> fix: stake token price normalize [skip cypress]

src/modules/governance/GovernanceTopPanel.tsx
=> feat: add governance-v2-link

src/hooks/governance/useProposalVotes.ts, src/modules/governance/proposal/VotersListItem.tsx
=> feat: added ENS names to voters list

src/components/SearchInput.tsx, src/components/transactions/AssetInput.tsx, src/components/transactions/Switch/SwitchAssetInput.tsx, src/components/transactions/Switch/SwitchModalContent.tsx, src/locales/en/messages.po
=> feat: add search modal for swap assets

public/icons/tokens/fdusd.svg
=> chore: fix icon

src/components/transactions/Switch/SwitchModal.tsx
=> feat: fork function for swap

src/ui-config/TokenList.ts
=> Feat/ add staking tokens to switch

pages/staking.staking.tsx
=> feat: add stkABPTV2 to total tvl in staking page

src/layouts/MainLayout.tsx
- Removes staking notification
---
=> chore: remove notify banner

cypress/e2e/3-stake-governance/stake.cy.ts
=> fix: abpt staking tests

pages/staking.staking.tsx, src/components/ConnectWalletPaperStaking.tsx, src/modules/staking/StakingPanelNoWallet.tsx
…oading on general staking data
- Adds ABPT v2 to no connection view in staking
- Deletes ABPT v1 from no connection view in staking
- Fixes loading state in header data
---
=> feat: ABPT no connection page fixes

src/layouts/MainLayout.tsx
=> Revert "chore: remove notify banner"

src/components/transactions/Withdraw/WithdrawAndSwitchModalContent.tsx, src/hooks/useWrappedTokens.tsx
- Key on market name instead of chain id
---
=> fix: wrapped token config

src/ui-config/networksConfig.ts
- Adds in reserve rate history endpoints for Scroll, BNB, and Gnosis
=> feat: rate history for new markets

src/components/transactions/Bridge/BridgeModal.tsx, src/components/transactions/NetworkSelect.tsx
=> feat: init UI

src/components/transactions/Switch/SwitchAssetInput.tsx
- Fixes image on select dropdown for swaping some bridged assets
---
=> fix: asset image in select

cypress/e2e/1-v3-markets/0-ethereum-v3-market/0-assets/dai.ethereum-v3.cy.ts, cypress/fixtures/assets.json
=> fix: dai coverage

src/libs/web3-data-provider/Web3Provider.tsx, src/modules/dashboard/lists/BorrowAssetsList/BorrowAssetsListItem.tsx
- Adds in a workaround for a bug that's present in chrome/MM. See code comment for details.
---
=> fix: retry MM activation after timeout

src/layouts/MainLayout.tsx
=> chore: stk message

src/components/transactions/Switch/SwitchActions.tsx, src/store/poolSlice.ts
- Adds in the option to specify the approval amount when generating the approval
- Uses new option in the switch widget
---
=> fix: approved amount

src/layouts/AppFooter.tsx
- Fixes lens link in the footer issue: #2000 
---
=> fix: wrong lens link in footer

cypress/e2e/1-v3-markets/3-polygon-v3-market/0-assets/eurs.polygon-v3.cy.ts
=> fix: skip eurs on polygon v3

cypress/e2e/1-v3-markets/3-polygon-v3-market/0-assets/eurs.polygon-v3.cy.ts, src/ui-config/marketsConfig.tsx
- Updates Metis subgraph url, current one is being deprecated
---
=> chore: updated metis subgraph url

src/ui-config/networksConfig.ts
- Reenables metis pokt rpc
---
=> chore: re-enable metis rpc

src/components/transactions/Switch/SwitchActions.tsx
- Use correct network when estimating gas for switch transactions
---
=> fix: switch gas estimation error

cypress/e2e/1-v3-markets/6-base-v3-market/e-mode.base-v3.cy.ts
- temp skip of cypress test failing due to borrow cap reached
---
=> fix: cypress tests

.github/workflows/build-test-deploy-dev.yml, .github/workflows/build-test-deploy.yml, cypress/configs/general.config.ts, cypress/e2e/1-v3-markets/10-metis-v3-market/general.metis-v3.cy.ts, cypress/e2e/1-v3-markets/11-scroll-v3-market/general.scroll-v3.cy.ts, cypress/e2e/1-v3-markets/9-harmony-v3-market/general.harmony-v3.cy.ts, cypress/fixtures/assets.json, cypress/support/steps/configuration.steps.ts
- General test for harmony
- General test for metis
- General test for scroll
---
=> test: general coverage for harmony metis and scroll

src/layouts/MainLayout.tsx
- updates notify banner text
---
=> chore: emission text

cypress/e2e/1-v3-markets/10-metis-v3-market/general.metis-v3.cy.ts
=> test: fix general metis test

src/ui-config/marketsConfig.tsx
- Adds in tx history for Gnosis, BSC, and Scroll markets
---
=> feat: tx history for markets

src/layouts/MainLayout.tsx
=> chore: banner text

pages/staking.staking.tsx, src/components/incentives/IncentivesButton.tsx, src/modules/staking/StakingPanel.tsx
- Adds in a '+' to the merit badge
- Moves badge on staking page to be below the staking apr
---
=> fix: merit badge

pages/_app.page.tsx
=> chore: disable track

src/ui-config/networksConfig.ts
-  Temporarily disable pokt rpc since public ones seem more stable right now
=> fix: scroll rpc [skip cypress]

package.json, src/services/UIPoolService.ts, yarn.lock
- Removes check for which data provider to use based on pool version since all payloads are executed
- Updates utils with latest package that has fix for fixing total liquidity calcs
---
=> fix: pool version check and liquidity calcs [skip cypress]

src/components/MarketSwitcher.tsx, src/modules/dashboard/DashboardContentWrapper.tsx, src/modules/markets/MarketsTopPanel.tsx
=> feat: fix fork config

src/ui-config/TokenList.ts
- adds gho swaps on arb 
- updates to new gho icon
---
=> feat: allow gho swap [skip cypress]

src/ui-config/networksConfig.ts
=> feat: deleted deprecated key [skip cypress]

src/helpers/useTransactionHandler.tsx
- Fixes a bug where existing approvals weren't cleared if they no longer exist. This caused an issue related to wrapping/unwrapping the markets base asset.
---
=> fix: clear approvals if no approval transactions

.github/pull_request_template.md, src/libs/web3-data-provider/WalletConnectConnector.ts, src/libs/web3-data-provider/Web3Provider.tsx
=> fix: build

pages/_app.page.tsx, src/modules/dashboard/DashboardContentWrapper.tsx, src/modules/markets/MarketsTopPanel.tsx, src/utils/mixPanelEvents.ts
=> chore: mx panel [skip cypress]

src/ui-config/TokenList.ts
=> chore: update aave logo [skip cypress]

src/utils/utils.ts
- Add Superfest incentive on wETH and ETH
- disable Superfest incentives on weETH supply and USDC and wETH borrow
---
=> feat: update Superfest campaign [skip cypress]

src/ui-config/marketsConfig.tsx
=> fix: temp disable avax incentives [skip cypress]

src/ui-config/marketsConfig.tsx
=> Revert "fix: temp disable avax incentives " [skip cypress]

src/components/incentives/IncentivesTooltipContent.tsx, src/ui-config/marketsConfig.tsx
=> Fix/avax fixes [skip cypress]

src/utils/utils.ts
Add the superfest icon to wstETH supply (base)
---
=> feat: add superfest icon to wstETH supply (base)

package.json, src/components/incentives/IncentivesTooltipContent.tsx, yarn.lock
- Fixes issue with incorrect incentives 
---
=> fix: decimal incentives [skip cypress]

package.json, yarn.lock
=> fix: incentives apy [skip cypress]

src/ui-config/marketsConfig.tsx
=> chore: disable temp swaps [skip cypress]

cypress/e2e/4-gho-ethereum/helpers/token.helper.ts
- Updates donor address for cypress test setup
---
=> fix: cypress test [skip cypress]

src/hooks/paraswap/common.ts, src/hooks/paraswap/useParaswapRates.ts
- Uses address book for fee claimer
---
=> fix: paraswap fee claim address [skip cypress]

src/layouts/MainLayout.tsx
- adds banner for new market
---
=> chore: market banner [skip cypress]

src/layouts/AppFooter.tsx
=> fix: terms link [skip cypress]

src/components/transactions/FlowCommons/RightHelperText.tsx
- Updated default approval method for smart contract accounts
The current signature validation scheme in ERC-2612:, based on V, R, S parameters, restricts signature validation to EOA wallets.
With the growing popularity of smart contract wallets, selecting the default approval method as transaction for smart contract wallets will reduce the rate of failed transactions. 
---
=> feat: updated default approval method for smart contracts

src/ui-config/TokenList.ts
- Adds ability to switch USDS
---
=> feat: add usds for switch

src/components/incentives/IncentivesTooltipContent.tsx, src/utils/utils.ts
- Update map for a token incentives
---
=> feat: incentives icon [skip cypress]

src/components/incentives/IncentivesTooltipContent.tsx
- Updates incentives token symbols
---
=> fix: update incentive symbols [skip cypress]

src/layouts/AppHeader.tsx
=> chore: update faq

.github/workflows/build-test-deploy-dev.yml, .github/workflows/build-test-deploy.yml, .github/workflows/test-deploy-fork.yml, .github/workflows/update-prod-staging.yml
- Update pinata-action version to avoid using cloudflare getaway
=> bump pinata-action version

src/components/incentives/IncentivesButton.tsx, src/components/incentives/IncentivesTooltipContent.tsx, src/components/incentives/MeritIncentivesTooltipContent.tsx, src/components/transactions/StakeCooldown/StakeCooldownModalContent.tsx, src/hooks/useMeritIncentives.ts, src/modules/dashboard/lists/BorrowAssetsList/BorrowAssetsListItem.tsx, src/modules/dashboard/lists/BorrowAssetsList/BorrowAssetsListMobileItem.tsx, src/modules/dashboard/lists/BorrowedPositionsList/BorrowedPositionsListItem.tsx, src/modules/dashboard/lists/ListAPRColumn.tsx, src/modules/dashboard/lists/SuppliedPositionsList/SuppliedPositionsListItem.tsx, src/modules/dashboard/lists/SuppliedPositionsList/SuppliedPositionsListMobileItem.tsx, src/modules/dashboard/lists/SupplyAssetsList/SupplyAssetsListItem.tsx, src/modules/dashboard/lists/SupplyAssetsList/SupplyAssetsListMobileItem.tsx, src/modules/markets/MarketAssetsListItem.tsx, src/modules/markets/MarketAssetsListMobileItem.tsx, src/modules/staking/StakingPanel.tsx, src/modules/staking/StakingPanelNoWallet.tsx, src/utils/utils.ts
The new "Supply cbBTC / Borrow USDC" action is coming very soon to Merit.
This PR implement the necessary refactoring to accept any Merit actions (other than just stkGHO APR currently).
Recap:
- refactored the `MeritIncentivesButton` & `useMeritIncentives`
- merge the logic of getting specific user apr & global apr to only 1 hook and component
- create a unique source of data (`symbolToMeritData`) for Merit incentives, in order to easily add other Merit incentives in the future.
- Include aUSDC to IncentivesSymbolMap
For now the API return is mocked because the route is not yet available. So you can now test these different cases:
- no wallet connected => use the average Merit APR (should show an APR of 8%)
- wallet connected but user not eligible for merit => use the average Merit APR …
=> ✨ Implement new cbBTC/USDC Merit Action aprs

src/components/incentives/MeritIncentivesTooltipContent.tsx, src/hooks/useMeritIncentives.ts, src/layouts/MainLayout.tsx, src/locales/en/messages.po
- adds more information about cbbtc and usdc merit 
---
=> Fix/merit incentives [skip cypress]

src/hooks/useMeritIncentives.ts
Fix Merit USDT tooltip on USDT Borrow
---
=> fix: usdt tooltip [skip cypress]

src/modules/migration/MigrationListItem.tsx
=> fix: color bug

src/components/transactions/Bridge/BridgeConfig.ts, src/hooks/generic/useTokensBalance.ts
=> fix: gho feetoken in testnet

src/layouts/MainLayout.tsx
- Fixes incentives message route
---
=> fix: base incentives [skip cypress]

src/components/transactions/Bridge/BridgeConfig.ts
- Re-enables GHO as a fee token for bridging
---
=> chore: re-enable gho as fee token

src/modules/staking/GetABPTokenModal.tsx
fixes #2256 
This change only updates a link to an external protocol.
---
=> fix: update balancer link

package.json, src/ui-config/marketsConfig.tsx, yarn.lock
- Enable debt switch on Lido and EtherFi
TODO:
---
=> feat: debt swith adapters [skip cypress]

src/layouts/MainLayout.tsx
- updates banner for merit pyusd rewards
---
=> chore: banner incentives text

src/layouts/MainLayout.tsx
=> Revert "chore: banner incentives text"

src/components/incentives/IncentivesTooltipContent.tsx, src/hooks/useMeritIncentives.ts
This PR add the new APRs of Avalanche Merit rewards.
These merit rewards replace the current LM on avalanche.
~For now APRs are mocked.
We're working on publishing the APR ASAP.~
=> APR are now available
---
=> ✨ feat: add avalanche lm new merit actions

src/layouts/MobileMenu.tsx, src/locales/en/messages.po
- Adds watch mode to mobile menu 
---
=> fix: add watch to mobile menu [skip cypress]

.github/actions/analyze-comment/action.yml, .github/actions/upload-artifacts/action.yml, .github/workflows/build-test-deploy.yml, .github/workflows/update-prod-staging.yml
=> chore: ci fix

src/ui-config/wagmiConfig.ts
- Providers public rpc to use as fallback
---
=> fix: provide fallback rpcs

.github/actions/cypress/action.yml, .github/workflows/build-test-deploy-dev.yml, .github/workflows/build-test-deploy.yml
=> adding build for cypress test

package.json, yarn.lock
=> chore: update aave-address-book

src/components/transactions/MigrateV3/MigrateV3ModalContent.tsx, src/modules/migration/MigrationListItem.tsx
- Fixes re-render issue in migration modal
---
=> fix: migrate modal re-renders

cypress/e2e/1-v3-markets/6-base-v3-market/swap.base-v3.cy.ts
- Skip the swap tests on Base for now
---
=> fix: temp skip base swap tests

src/components/transactions/Bridge/BridgeConfig.ts
Update CCIP mainnet & testnet token pools following [Proposal 236](https://app.aave.com/governance/v3/proposal/?proposalId=236)
---
=> 🆕 update ccip token pool addresses [skip cypress]

.github/actions/analyze-comment/action.yml, .github/actions/cypress/action.yml, .github/actions/upload-artifacts/action.yml, .github/workflows/build-test-deploy-dev.yml, .github/workflows/build-test-deploy.yml
- upgrade update-artifact actions to version v4
=> upgrade upload-artifact version [skip cypress]

.github/workflows/update-prod-staging.yml
=> matching verions for artifacts

src/ui-config/marketsConfig.tsx, src/ui-config/networksConfig.ts
=> chore: update op branding

src/ui-config/networksConfig.ts, src/ui-config/wagmiConfig.ts
- Adds in rate history endpoint for Linea markets
- Adds in wagmi chain id to network config so we don't have to maintain a separate list of supported chains
- Splits networkConfigs up to test and prod config
- Closes #2345 
---
=> feat: linea rates [skip cypress]

src/components/UserDisplay.tsx
- Fixes ENS avatar not getting displayed on the navbar
=> fix: ENS avatar not getting displayed on the navbar

src/layouts/MainLayout.tsx
=> chore: banner tex [skip cypress]

src/components/incentives/IncentivesCard.tsx, src/modules/dashboard/lists/BorrowedPositionsList/GhoBorrowedPositionsListItem.tsx, src/ui-config/networksConfig.ts
- Adds in rate history to Sonic market
- Fixes alignment of assets with multiple rewards
- Fixes height of 'Gho Rate' badge on borrow item
---
=> feat: sonic rates [skip cypress]

.github/workflows/build-test-deploy.yml, .github/workflows/update-prod-staging.yml
Removes CF action and rename workflow jobs
- …
---
=> remove cf action

src/ui-config/marketsConfig.tsx
- Adds in url for Sonic subgraph
---
=> feat: sonic subgraph [skip cypress]

package.json, public/icons/networks/celo.svg, src/ui-config/governanceConfig.ts, src/ui-config/networksConfig.ts, yarn.lock
- Adds in Celo network config
---
=> feat: celo network [skip cypress]

src/ui-config/networksConfig.ts
- Updates public rpc config on eth mainnet
---
=> fix: public rpc [skip cypress]

package.json, yarn.lock
- Bumps address book for latest gateway on gnosis
=> chore: address book bump [skip cypress]

src/hooks/useSonicIncentives.tsx
Update Sonic USDC.e points from 10x to 12x.
This is a request from Sonic Team.
---
=> chore: update sonic usdce points [skip cypress]

src/hooks/useMeritIncentives.ts
Implement borrow incentive on wstETH Base
[[ARFC] Joined incentive renewal - Prime, Arbitrum & Base](https://governance.aave.com/t/arfc-set-aci-as-emission-manager-for-liquidity-mining-programs/17898/70?u=nandy.eth)
---
=> feat: add Merit Base wstETH borrow campaign [skip cypress]

CONTRIBUTING.md, cypress/e2e/0-v2-markets/2-polygon-v2-market/0-assets/matic.polygon-v2.cy.ts, cypress/e2e/0-v2-markets/2-polygon-v2-market/swap.polygon-v2.cy.ts, cypress/e2e/0-v2-markets/3-avalanche-v2-market/0-assets/avax.avalanche-v2.cy.ts, cypress/e2e/0-v2-markets/3-avalanche-v2-market/0-assets/dai.avalanche-v2.cy.ts, cypress/e2e/0-v2-markets/3-avalanche-v2-market/0-assets/weth.avalanche-v2.cy.ts, cypress/e2e/1-v3-markets/0-ethereum-v3-market/0-assets/dai.ethereum-v3.cy.ts, cypress/e2e/1-v3-markets/0-ethereum-v3-market/0-assets/link.ethereum-v3.cy.ts, cypress/e2e/1-v3-markets/0-ethereum-v3-market/0-assets/usdc.ethereum-v3.cy.ts, cypress/e2e/1-v3-markets/0-ethereum-v3-market/0-assets/wbtc.ethereum-v3.cy.ts, cypress/e2e/1-v3-markets/0-ethereum-v3-market/0-assets/wsteth.ethereum-v3.cy.ts, cypress/support/steps/configuration.steps.ts, cypress/support/tools/tenderly.ts
- Updates cypress tests to use virtual testnets instead of forks
- Fixes broken tests due to frozen reserves
---
=> chore(e2e): migrate from tenderly forks to virtual testnets (#2397)

package.json, src/components/incentives/IncentivesTooltipContent.tsx, src/hooks/useMeritIncentives.ts, yarn.lock
=> Revert "feat: add eBTC campaign [skip cypress]"

src/libs/web3-data-provider/Web3Provider.tsx, src/ui-config/wagmiConfig.ts
- Sorts the connect kit connectors so that the family connector is last. This fixes an issue where wallet connection in the Safe UI was slow.
---
=> fix: safe app connection[skip cypress]

src/components/incentives/IncentivesTooltipContent.tsx, src/hooks/useMeritIncentives.ts
We lack the forum link for now, I'll add it as soon as we posted it
=> feat: add gnosis eure campaign

src/modules/reserve-overview/ReserveTopDetailsWrapper.tsx
Closes https://github.com/aave/interface/issues/2427
=> fix: back button in reserves when history is undefined

src/components/transactions/GovVote/GovVoteActions.tsx
- re fetches top voters after a user submits a vote
---
=> fix: refetch voters after vote submission

package.json, src/components/incentives/IncentivesTooltipContent.tsx, src/hooks/useMeritIncentives.ts, yarn.lock
Add new RLUSD campaign. Campaign will go live Tuesday April 22th at 3pm EST.
This PR can be merged before 3pm EST, campaign switch on is managed by ACI API endpoint
---
=> feat: add merit RLUSD campaign

src/hooks/useMeritIncentives.ts
- update Merit Avalanche campaigns' rules to add anti-loop
Forum links: https://governance.aave.com/t/arfc-set-aci-as-emission-manager-for-liquidity-mining-programs/17898/89?u=nandy.eth,
https://governance.aave.com/t/arfc-set-aci-as-emission-manager-for-liquidity-mining-programs/17898/88?u=nandy.eth
---
=> feat: update Merit Avalanche campaigns' rules

src/hooks/useEtherfiIncentives.ts
- Add multiplier for Ether.fi eBTC
PR ready for review (Note: I cannot add label to PRs on this repo. Can you grant this access please ?)
---
=> feat: add multiplier for Ether.fi eBTC

src/hooks/useMeritIncentives.ts, src/utils/utils.ts
- Add Base LBTC cbBTC MASIV campaign
Preview
---
=> feat: add Base LBTC cbBTC MASIV campaign and Kernel points

src/ui-config/reservePatches.ts
- Patches PT token name and symbol
---
=> chore: patch pt name and symbol [skip cypress]

package.json, src/hooks/useSonicIncentives.tsx, yarn.lock
=> feat: Add stS sonic lab points

src/components/incentives/IncentivesTooltipContent.tsx, src/hooks/useMeritIncentives.ts
Preview:
Campaign will be live May 6th. No need to wait until campaign been live as useMerit already manage campaign switch on and off
Campaign forum post: https://governance.aave.com/t/arfc-set-aci-as-emission-manager-for-liquidity-mining-programs/17898/94?u=nandy.eth
---
=> feat: add borrow gho on Base Masiv campaign

package.json, src/hooks/useEthenaIncentives.ts, yarn.lock
Allocated **2x Ethena Points** for PT sUSDe (May)
Allocated **1x Ethena Point** for PT sUSDe (July)
- <img width="712" alt="Capture d’écran 2025-05-13 à 16 10 26" src="https://github.com/user-attachments/assets/db23c7b5-d4d1-486f-a9a2-c14f28a12b36" />
- <img width="712" alt="Capture d’écran 2025-05-13 à 16 10 30" src="https://github.com/user-attachments/assets/f9239434-3cb7-451d-8d2d-6b0f1a7f6cb6" />
Incentive points are now active.
---
=> feat: add Ethena PT points

src/modules/dashboard/lists/BorrowedPositionsList/BorrowedPositionsListItem.tsx
- Disables debt switch functionality on some v2 markets given its not possible to borrow 
---
=> fix: debt switch

package.json, pages/api/rpc-proxy.ts, src/ui-config/governanceConfig.ts, src/ui-config/networksConfig.ts, yarn.lock
- Adds in network config for soneium network to support governance infrastructure per this proposal https://app.aave.com/governance/v3/proposal/?proposalId=312
---
=> chore: soneium network

src/components/transactions/Switch/BaseSwitchModalContent.tsx
=> fix: cow wrapped condition in op [skip cypress]

src/components/transactions/Warnings/ChangeNetworkWarning.tsx, src/hooks/stake/useUmbrellaSummary.ts, src/modules/reserve-overview/Gho/SavingsGho.tsx
- Show deposit button if no balance, but disable it
=> fix: sgho deposit button

src/components/WalletConnection/ConnectWalletButton.tsx, src/utils/events.ts
- Adds additional details about wallet connection flows
---
=> feat: wallet connect details

src/components/transactions/Bridge/BridgeConfig.ts
- Adds gho as a fee token on base
---
=> feat: gho as fee token on base

src/hooks/useSonicIncentives.tsx
Update Sonic points for Season 2
Points change have been communicated by Sonic Labs
---
=> [Merge June18th] feat: update Sonic incentives points for season 2

src/components/incentives/IncentivesTooltipContent.tsx, src/hooks/useMeritIncentives.ts
This pull request add Masiv incentives for [[ARFC] Base Incentive Campaign Funding](https://governance.aave.com/t/arfc-base-incentive-campaign-funding/21983)
Make sure these campaigns exist and add them if not:
Incentive will start Wednesday 23th, this PR must be in prod before campaign launch for efficency
---
=> feat: add Base Masiv incentives

src/components/incentives/IncentivesTooltipContent.tsx, src/components/incentives/MerklIncentivesTooltipContent.tsx, src/hooks/useMerklIncentives.ts, src/locales/en/messages.po
- Add customMessage + customForumLink + customClaimMessage to Merkl incentives
- Add Aave Ethereum USDe token wrapped to whitelisted tokens => token to whitelist for the new Ethena campaign
---
=> ✨ Add new USDe incentives + improve Merkl tooltip

src/layouts/MainLayout.tsx
- adds swap on all markets available with banner 
---
=> chore: banner

src/hooks/useMeritIncentives.ts
- Add Celo supply (USDT or ETH) borrow USDT incentive
- update Merit to always display biggest APR
Preview (with CELO_SUPPLY_MULTIPLE_BORROW_USDT APR hardcoded at 5%)
---
=> feat: add new Celo campaign

pages/sgho.page.tsx
- Fixes sgho bug causing crash when on a market not supported by gho 
---
=> fix: sgho issue

src/components/TransactionEventHandler.tsx
=> chore: add walletType to transaction event

src/layouts/MainLayout.tsx, src/layouts/TopBarNotify.tsx
=> fix: banner

src/components/incentives/IncentivesTooltipContent.tsx, src/hooks/useMerklIncentives.ts
- Updates reward token map on Arb
- Filter campaigns by chain id 
---
=> fix: filter Merkl campaign by chain id

src/ui-config/TokenList.ts
=> chore: adds RLUSD into swaps

src/components/incentives/MerklIncentivesTooltipContent.tsx, src/locales/en/messages.po
=> fix: apr to apy

src/modules/dashboard/lists/constants.ts
- enables showing USYC on horizon
---
=> chore: enable asset

src/components/transactions/Switch/cowprotocol/cowprotocol.constants.ts
Enabled GHO in arbi
https://explorer.cow.fi/arb1/orders/0xff762fba76ed9d796ce0802b9f64a428d28fc296b0fffd864dd792395bc0eb9f9fa3c00a92ec5f96b1ad2527ab41b3932efeda5868ca93eb
https://explorer.cow.fi/arb1/orders/0x26dfd034ef74daae0157b38782a61d1c13b8de86c75d820527260abaadef010a9fa3c00a92ec5f96b1ad2527ab41b3932efeda5868ca944d
=> feat: Enable GHO in Arbitrum

pages/api/rpc-proxy.ts
=> fix: plasma rpc

src/components/MarketSwitcher.tsx, src/layouts/MainLayout.tsx
=> fix: banner market

src/hooks/useEthenaIncentives.ts, src/hooks/useEtherfiIncentives.ts
- Added points for weETH, sUSDe and USDe on Plasma as required
---
=> feat: add points for ethena & etherfi

src/components/Analytics/AnalyticsConsent.tsx, src/store/analyticsSlice.ts
- helps to understand usage on opted in vs opted out
---
=> feat: track consent

src/components/transactions/Switch/cowprotocol/cowprotocol.helpers.ts, src/components/transactions/Switch/switch.types.ts, src/hooks/switch/cowprotocol.rates.ts, src/hooks/switch/useMultiProviderSwitchRates.ts, src/ui-config/queries.ts
- Closes ALE-9 : Send adapter appCode for CoW quotes in CollateralSwap
---
=> fix: send adapter appCode for CoW quotes in CollateralSwap

src/hooks/useMerklIncentives.ts
=> Revert "feat: add hardcoded apr for plasma usde" to delete hardcoded values fro incentives
