src/modules/markets/AssetsList.tsx

This PR:
1. Fixes assets sorting by symbol in Firefox. Currently, it doesn't work. For some reason, this code behaves differently in Chrome/Safari and Firefox:
```js
["DAI", "EURS", "USDC", "USDT", "sUSD", "AAVE", "RAI", "xSUSHI", "UNI"].sort(function(a, b ) { return b.toUpperCase() < a.toUpperCase() ? -1 : 0;})
```
To make it work in Firefox, I changed `0` to `1`. Chrome/Safari are not affected.
1. Fixes the order of sorting by symbol: ascending order is A to Z, descending is Z to A. Currently, it's the opposite.

Fix assets sorting by symbol

---

src/hooks/app-data-provider/useAppDataProvider.tsx

in js `Z < a` so `sUSD` is not properly sorted right now.
This fixe uppercases the symbol so the sorting is more reasonable.

fix: properly sort by symbol

---

src/modules/reserve-overview/ReserveConfiguration.tsx

Maybe it makes more sense to just hide row if reserve is not enabled as collateral to not show the 0%

fix: -100% as calcs from contract is 0 instead of 10000

---

src/modules/reserve-overview/ReserveTopDetails.tsx

Add block explorer link to underlying asset next to asset name
Also move oracle link to the bottom row

feat: add block explorer link for reserves

---

cypress/integration/1-v3-markets/2-avalanche-v3-market/reward.avalanche-v3.spec.ts
src/components/transactions/ClaimRewards/ClaimRewardsActions.tsx

In V2, when a user closes a supply or borrow position that is earning rewards, the IncentivesController contract stores these rewards in a separate variable and allows for claiming without passing this asset as a parameter
In V3, this variable was removed and now *all* assets must be passed regardless if the position is active or not.
There's no way to track previous supply/borrow positions, so for v3, all a/s/v tokens with incentives must be passed as the `assets` parameter to `claimRewards`.

fix: ability to claim rewards for supply/borrow positions that are withdrawn

---

src/components/transactions/Withdraw/WithdrawModalContent.tsx

Currently when the max withdraw button is pressed, the amount is calculated by requiring that collateral * (liquidationThreshold + cushion) is remaining. This results in users being forced to keep a large amount of collateral to cover a small borrow position as shown below.
This changes the calculation to require a minimum health factor of 1.07 (to be consistent with borrow logic), which allows users to withdraw a greater potion of their collateral (in scenario below user could now withdraw up to 14998.6 DAI).

fix: calculation of max withdrawable amount

---

pages/governance/proposal/index.governance.tsx

Fixes a funky edge case on `http://localhost:3000/governance/proposal/?proposalId=0` which would never load as `!0` evaluates to `true` leading to a `skip`
This fix works around that issue by increasing specificity on the comparison

fix: allow dynamic proposal fetching for proposal 0

---

src/modules/governance/proposal/VoteInfo.tsx

You can only vote once per address & proposal.
Flipping your vote is not possible as you could swing elections that way & mislead other participants.
- closes https://github.com/aave/interface/issues/742

fix: disable voting after vote was casted

---

src/components/transactions/FlowCommons/Success.tsx

After a tx, there's a modal that allows users to add tokens to their wallet which currently has the decimals for this token hardcoded to 18.

fix: use correct decimals when adding token to wallet

---

.github/release-template.md
.github/workflows/build-test-deploy.yml
.github/workflows/deploy-prod.yml

Closes https://github.com/aave/interface/issues/723
On every deploy to production:
* Create git tag `release-YYYY-MM-DD_HH-mm`
* Create Github release with up-to-date IPFS links
* Attach built app files to release as and artifact
Would look something like this: 
Example draft release (not visible publicly): https://github.com/aave/interface/releases/tag/untagged-4d812ba21369d74f0141

ci: create GH release on deploy to prod

---

cypress/integration/1-v3-markets/5-fantom-v3-market/0-assets/weth.fantom-v3.spec.ts
src/ui-config/stakeConfig.ts

Currently when testnet mode is enabled, the staking page switches the data source to Kovan which is confusing and leads people to believe their staked assets are missing.
This switches the staking page to always use data from Eth Mainnet

feat: always use mainnet for staking data source

---

src/modules/governance/FormattedProposalTime.tsx
src/modules/governance/utils/formatProposal.ts

https://ycharts.com/indicators/ethereum_average_block_time#:~:text=Ethereum%20Average%20Block%20Time%20is,from%2013.25%20one%20year%20ago.

fix: account for difficulty increase

---

package.json
src/locales/en/messages.po
src/modules/reserve-overview/ReserveTopDetails.tsx
src/ui-config/reservePatches.ts

using parameterless render functions like `  const ReserveIcon = () => {` results in a complete remount on every state dispatch (1x per second). It's completely unnecessary here.
- adds svg optimization to lint-staged
- fixes issue with mixed case symbol names

fix: exit render loop

---

src/components/MarketSwitcher.tsx
src/ui-config/marketsConfig.tsx
src/ui-config/networksConfig.ts

- Display testnet icon
- Make market names consistent
- Change ordering to place ETH testnets together
Old
New

refactor: make ropsten config more consistent with other markets

---

.github/workflows/build-fork.yml

dependabot prs are the ones most responsible for irregular bundle size increase. yet, the analyzer ci does not run on these prs.
This pr changes the ci to run the fork workflow on dependabot prs.

ci: run fork ci on dependabot prs

---

src/modules/governance/ProposalsList.tsx
src/modules/governance/utils/formatProposal.ts

Fetches pending proposals in parallel instead of fetching them in sequence
Removes unnecessary `getBlockNumber` call
Ppl reported https://app.aave.com/governance/ being slow, especially when the ache is outdated - this improves the situation.

perf: parallelize & reduce calls on governance

---

src/modules/governance/utils/getProposalMetadata.ts

In the 1inch proposal https://gateway.pinata.cloud/ipfs/QmPccptdeMjEAUbJLEXRw8s8dnWq6aVdigaqMUJGQJQBGV is referenced as ipfs instead of https://gateway.pinata.cloud/ipfs/QmeGHtzBASPj2tQyMZnBpiFghbZvawgx4kJ6HJMNUM4EY4 so the json() parser breaks as it's not a json.
This pr will clone the stream (as you can only read it once) and first try to parse it to json, if it's not successfull it will parse it as text.
Late night fix, but this fixes the ui

fix: don't break on md ipfs [skip cypress]

---

src/ui-config/marketsConfig.tsx

#937 removed the caching server from usage with staking data. This appears to have caused an error with the ETH Mainnet reserves data cache. 
Reserves and user reserves data are returned successfully, but incentives fail to load causing a blank screen. By disabling the caching server for ETH Mainnet and fetching all data via RPC queries, the issue is resolved.

fix: disable caching server for eth mainnet v2 market

---

src/ui-config/marketsConfig.tsx
src/utils/apolloClient.ts

- contains the actual fix for the problem quickfixed in #971 (forgot to pass the http handler to split) which lead to the first graphql endpoint to fail
- disables caching on amm

cleanup: disable caching on amm

---

src/utils/hfUtils.ts

Ensure that the calculated remaining debt is never less than 0 when determining new health factor. Fixes a bug where the new health factor in the repay modal was showing as a large negative number when repaying full debt.
closes #763

fix: prevent remaining debt from being negative in hf calculation

---

jest.config.js
jest.setup.js
package.json
src/components/__tests__/example.test.ts
yarn.lock

- adds in `jest` and supporting packages with RTL support
- adds a Nextjs-compatible config
- adds a `test` and `test:ci` command that can be run in CI
- adds an example test to prove the `test` command works effectively
- ignores any coverage testing for now

chore: add in unit testing scaffolding

---

src/hooks/useAddressAllowed.tsx

Ensure we get a response in the 200 range before trying to parse

fix: handle screening api 500 errors [skip cypress]

---

src/components/transactions/AssetInput.tsx

- Resolves https://github.com/aave/interface/issues/836
- Added clear button for asset input through `CancelIcon`
- Render button when value is present
- On click, clears value

Feat: added clear button for asset input

---

pages/governance/ipfs-preview.governance.tsx
pages/governance/proposal/[proposalId].governance.tsx
pages/governance/proposal/index.governance.tsx
src/modules/governance/ProposalsList.tsx

adds a hidden page which can be used to preview an ipfs hash. This is to prevent issues like the one with oneInch where a wrong ipfs hash was submitted.
- closes #984 #985

feat: governance UI hash preview

---

src/components/infoModalContents/ApprovalInfoContent.tsx

- Fixes https://github.com/aave/interface/issues/746
- Added space character before FAQ button
Note - once this has been merged, we can close the stale PR https://github.com/aave/interface/pull/938

Fix: added space before FAQ

---

src/components/transactions/Repay/RepayModalContent.tsx

fix: ordering and available amounts in repay modal

---

.github/actions/private-ipfs-pin/action.yml
.github/workflows/update-prod-staging.yml

This addition to worklow:
1. Authenticates to Google Kubernetes cluster (GKE)
2. Uploads the build there
3. Invokes the command to pin the build to IPFS Cluster running inside the GKE
This way we avoid exposing IPFS cluster API to the outside world. Also this is much faster than uploading build directly via exposed IPFS cluster API.

ci: pin to self-hosted IPFS cluster

---

src/components/transactions/AssetInput.tsx

- Fixes https://github.com/aave/interface/issues/1050
- Simply render the `IconButton` component i.e. the clear button right after the `InputBase` component
- Update its `z-index` to ensure it is clickable when rendering next to the asset dropdown
- Update its rendering condition to not render if `disabled` is truthy
Screenshot 👇

Fix: fixes clear button not visible on asset input

---

src/modules/dashboard/LiquidationRiskParametresModal/LiquidationRiskParametresModal.tsx
src/modules/dashboard/LiquidationRiskParametresModal/components/InfoWrapper.tsx
src/modules/dashboard/LiquidationRiskParametresModal/components/LTVContent.tsx

If the LTV is grater than the Max LTV, then the line will show as red:
I cleaned up some of the logic while in here. I lifted the calculations up to the parent component and then just pass in the alert colors down to the child components.
closes #891

fix: liquidation risk colors

---

cypress/e2e/0-v2-markets/0-main-v2-market/critical-conditions.aave-v2.cy.ts
src/modules/markets/AssetsListItem.tsx

Adds a check to make sure `borrowingEnabled` is true in addition `stableBorrowRateEnabled` in order to show the borrow apy.
It's possible that stable borrow could still be enabled, but borrowing is disabled on the asset, which takes precedence.

fix: only show stable borrow rate if borrowing is enabled

---

cypress/e2e/0-v2-markets/0-main-v2-market/critical-conditions.aave-v2.cy.ts
src/libs/hooks/use-get-ens.tsx
src/utils/marketsAndNetworksConfig.ts

The primary RPCs used on the app are from POKT and have a customizable contract allowlist. Since it is not feasible to add all ENS resolvers to the allowlist, lookups return an error with the POKT rpc, so this PR switches to using the public rpc for ens lookups.
Addresses to test:
0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045 - vitalik.eth
0x064Bd35c9064fC3e628a3BE3310a1cf65488103D - hello.eth

fix: switch to using public eth rpc for ens lookups

---

src/ui-config/governanceConfig.ts

Piñata public gateway has been getting frequent errors causing governance cache to not be updated.
This switches to the cloudflare public gateway which should hopefully be more reliable.

feat: switch governance gateway to cloudflare

---

yarn.lock

- Fixes this warning in the console:
```
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
```

chore: bump browserslist package

---

package.json

Simplified some of the lint-staged config and also added a step to run prettier and write the changes to the file before committing. This should ensure that any files with changes will always get formatted according to our prettier config.

chore: add prettier to lint-staged

---

src/ui-config/governanceConfig.ts

Roll back changes from #1115 due to CORS errors

fix: rollback governance gateway change [skip cypress]

---

src/modules/reserve-overview/graphs/InterestRateModelGraph.tsx
src/modules/reserve-overview/graphs/InterestRateModelGraphContainer.tsx

Removes the Supply APY from the interest rate model graph.
Supply APY isn't directly correlated with utilization rate so we can't accurately show it on this graph.

fix: remove supply APY from interest rate model graph

---

src/components/transactions/Borrow/BorrowModalContent.tsx

Remove duplicate warning in borrow modal about debt ceiling

fix: remove duplicate debt ceiling warning

---

pages/governance/ipfs-preview.governance.tsx
pages/governance/proposal/index.governance.tsx
src/modules/governance/ProposalsList.tsx
src/modules/governance/utils/getProposalMetadata.ts
src/ui-config/governanceConfig.ts

- Uses the retry logic anywhere we try to fetch proposal data from the public ipfs gateways
- Removes the piñata public gateway and adds ipfs.io gateway in its place
Having headers on the request to the gateway was giving a CORS error on ipfs.io, so I removed it. Both configured gateways are working without the header.

fix: use gateway retry logic anywhere we fetch ipfs data

---

.github/dependabot.yml
.github/workflows/dependency-review.yml

- Adds in a Github action to scan for dependency vulnerabilities in PRs
- Add deliberate labels for Dependabot PRs
- `dependencies`
- `Ready for Dev Review`
After this housekeeping PR is merged, we should remove the `javascript` label.

chore: add dependency scanning for PRs

---

package.json
src/components/WalletConnection/WalletSelector.tsx
src/layouts/WalletWidget.tsx
src/libs/web3-data-provider/WalletOptions.ts
src/libs/web3-data-provider/Web3Provider.tsx

- Fixes an issue where the watch mode only address would not re-populate on page load in some cases
The main issue with treating the watch mode address different from other providers, is that the state wasn't getting cleared out. So for example, if you were connected MM, and then you enter in a watch address, we'd still keep around the provider info for MM in local storage. I think that's what was causing some issues on page load, there'd be a race condition with loading the provider and loading the watch mode address.
I did a little refactoring around how the watch mode address is handled. I ended up making a `WatchModeOnlyConnector`. The connector stubs out the required methods and takes care of setting and clearing local storage for the `watchModeOnlyAddress`. Going this route lets us …

fix: made connecting with watch mode on page load more reliable

---

src/hooks/useReservesHistory.tsx
src/modules/reserve-overview/ReserveConfiguration.tsx

Disabled charts for AMPL which does not have accurate subgraph data due to the rebasing events not being indexed
---

fix: disable charts for broken assets

---

.github/workflows/build-test-deploy.yml
.github/workflows/test-deploy-fork.yml
.github/workflows/update-prod-staging.yml

- Fixes pinning to Pinata IPFS in CI  
See this PR for changes to `pinata-action`:
https://github.com/aave/pinata-action/pull/6
In short: Pinata api had a breaking change that caused failures in pinata Github action 
---

fix: update pinata action

---

cypress/e2e/0-v2-markets/0-main-v2-market/0-assets/bat.aave-v2.cy.ts
cypress/e2e/0-v2-markets/0-main-v2-market/0-assets/ren.aave-v2.cy.ts

Skipping bat.aave-v2.cy.ts test since it was disabled.

Skip BAT and REN on V2 ETH Market

---

cypress/e2e/0-v2-markets/2-polygon-v2-market/0-assets/ghst.polygon-v2.cy.ts
cypress/e2e/1-v3-markets/4-optimism-v3-market/0-assets/usdt.optimism-v3.cy.ts
cypress/e2e/1-v3-markets/4-optimism-v3-market/e-mode.optimism-v3.cy.ts
src/ui-config/networksConfig.ts

#1073 added a custom rotation provider which supports any number of fallback rpcs as opposed to ethers.FallbackProvider which was limited to 1
- Adds additional public rpc fallbacks from chainlist.org to all networks
- Specifically fixes issue with ETH Goerli RPCs

chore: add additional public rpcs to all networks

---

src/hooks/useReservesHistory.tsx

- Hides graphs for the FEI USD frozen asset due to bad data coming from either the subgraph or backend
This is a temporary solution to just _not show bad data_ for this asset.  The longer term fix is investigating the data issues and writing code that will prevent it from happening further.  We can then decide if/when to turn the graphs back on for this reserve after and if that data has been fixed.
---

fix: hide historical graphs for FEI USD on eth mainnet v2

---

src/store/utils/queryParams.ts

- closes https://github.com/aave/interface/issues/1300
In zustand native browser apis are used to set and read query parameters.
This introduced some issues as some of next router logic is built around not only the browser history but also internal state which get out of sync. Apparently you can just use `Router` singleton exported by `next/router` for exactly that purpose.

fix: use next router for pushing route

---

package.json
src/hooks/useAssetCaps.tsx
src/store/protocolDataSlice.ts
src/store/root.ts
src/store/utils/queryParams.ts
yarn.lock

- bump visx/tooltip: resolves strict mode error
- maintain current query parameters when adding a new query parameter: issue get's visible when e.g. directly going to https://app.aave.com/reserve-overview/?underlyingAsset=0x7f5c764cbc14f9669b88837ca1490cca17c31607&marketName=proto_optimism_v3
- optimize boot: only set the market from localStorage when it's different to the server rendered one
- "optimize" getAssetCapData: When you declare the function inside, every time the component is rendered the function will be defined again. That said, with this fix applied, the initial page load for this page is still crappy as it returns `null` and does not even render a layout. I don't understand why a context is used here, but also didn't have time to further clean this up.

fix: maintain query parameters

---

cypress/e2e/2-settings/wallet-connect.cy.ts
cypress/support/e2e.ts
src/components/AddressBlocked.tsx
src/libs/web3-data-provider/Web3Provider.tsx

- Disable screening endpoint call for mocked address
To test: check different combinations of connecting, disconnecting, and switching between normal and mocked wallet and check that no request is made to `https://aave-api-v2.aave.com/addresses/status?address` for mocked wallet
Does not use existing `watchModeOnlyAddress` parameter which is exported from Web3Provider because `currentAccount` and `watchModeOnlyAddress` are updated asyncronously
---

chore: screening optimisations

---

src/utils/__tests__/RotationProvider.test.ts
src/utils/rotationProvider.ts

RotationProvider currently operates with no limitation on error callbacks, so if a transaction has failing gas estimation the provider will continue to retry and throw errors indefinitely. This adds a limit to the maximum number of loops through the array of rpc providers before throwing an error.
---

chore: replace rotationDelay with check on max retries

---

src/components/transactions/Supply/SupplyModalContent.tsx

- Fixes a bug where an asset being supplied could show as enabled for being used as collateral, when it is disabled on the pool reserve 
I just expanded on the logic for detecting the collateral type, so if `poolReserve.usageAsCollateralEnabled` is false, it will take precedence over everything else.
---

fix: show collateral as disabled if it is disabled on the reserve

---

cypress/e2e/1-v3-markets/3-polygon-v3-market/e-mode.polygon-v3.cy.ts
cypress/e2e/2-settings/wallet-connect.cy.ts
src/components/AddressBlocked.tsx
src/libs/web3-data-provider/Web3Provider.tsx
src/modules/reserve-overview/ReserveActions.tsx

- Fixes a bug where the app was not working inside of the gnosis safe UI
It's not clear exactly why this caused an issue, but calling `setAccount` (which changed global app state) inside of the connect wallet callback was causing the connect logic to fire multiple times.
---

fix: don't clear account in connect wallet callback

---

src/modules/reserve-overview/ReserveActions.tsx

Addresses the following issue created: https://github.com/aave/interface/issues/1388
---

fix: remove borrow button when borrowing is disabled for asset on overview page

---

pages/governance/proposal/[proposalId].governance.tsx

Setting React markdown to render tables properly
Tables are currently completely broken.
Before:
After:
---

fix: make tables in markdown render somewhat correctly

---

src/ui-config/networksConfig.ts

The app uses arbiscan for mainnet, which objectively is the better explorer. It's not clear why for testnet it doesn't.
Using arbiscan always.
---

feat: use arbiscan on test and prod

---

src/store/protocolDataSlice.ts
src/ui-config/permitConfig.ts

New V3 test markets are not added to `permitConfig`, so these assets are not setup to use permit for approval. This defaults to enable permit for all V3 testnet assets.
- …
---

feat: remove individual config and default to enable permit for all v3 testnet assets

---

src/utils/getMaxAmountAvailableToBorrow.ts

- Closes #1494 to factor available liquidity into max available to borrow calculation
- `formattedAvailableLiquidity` is converted based on `reserve.decimals`
---

fix: max available to borrow calculation

---

src/modules/dashboard/lists/SupplyAssetsList/SupplyAssetsListItem.tsx
src/modules/dashboard/lists/SupplyAssetsList/SupplyAssetsListMobileItem.tsx

- Let assets with max supply cap reached to be displayed in the supply list but disabled
- `SupplyAssetsListItem` and `SupplyAssetsListMobileItem` no longer returns null if `supplyCapUsage.isMaxed`
---
Close #1500

feat: display asset with max supply cap

---

src/components/MarketSwitcher.tsx

- Fixes a bug where the market switcher dropdown icon wasn't positioned correctly in some cases.
To reproduce the bug, go to the Governance page and refresh the page. Then navigate to the Dashboard or Markets page.
This bug happens because when you load the app on the governance page, the default styles are loaded for the MuiSelect component, which includes a padding right of 32px. When you navigate to the dashboard, our custom styling overrides the default and sets a padding of 0. If you start on the dashboard, the default styles take precedence over our custom styling, so the padding right is applied.
---
Please ensure you, as the …

fix: don't override default padding right for MuiSelect in market switcher

---

src/locales/en/messages.po
src/modules/dashboard/lists/ListHeader.tsx

- Fixes bug [#1576](https://github.com/aave/interface/issues/1576)
The problem is there is an extra list-column in headers of the ListLoader. After this was removed, the skeletons align properly.
<details>
<summary>Before</summary>
<br />
</details>
<details>
<summary>After</summary>
<br />
</details>
---

Fix: Remove extra header column in ListLoader

---

src/components/transactions/Swap/SwapModalContent.tsx

- Fixes a bug where the swap target would incorrectly say a user was entering isolation mode when trying to swap the entire amount of a collateral.
Context: if you have only 1 asset supplied, or only 1 asset enabled as collateral, and you try to swap the entire amount to an isolated asset, you will enter isolation mode. The swap details will indicate this on the collateral type of the swap target.
---

fix: make sure reserve can be an isolated asset

---

src/store/poolSlice.ts

- Use max uint value for approval amount tx. This was previously a value slightly smaller than the max, but with the UNI contract, the approval tx will fail if the amount is greater than 96 bits (and not the max value) https://github.com/Uniswap/governance/blob/eabd8c71ad01f61fb54ed6945162021ee419998e/contracts/Uni.sol#L149
---

fix: use max uint value for approval amount

---

src/components/MarketSwitcher.tsx

chore: update version banner

---

src/components/WalletConnection/WalletSelector.tsx

- Remove auto focus on input for entering address for 'read-only' mode. The input was getting focus when clicking on a wallet option, causing weird UX
---

fix: remove auto focus on address input

---

src/components/transactions/DebtSwitch/DebtSwitchModalContent.tsx
src/store/poolSlice.ts

- When switching max amount, pass in max uint value in transaction
- Use `symbol` prop for asset target input so correct name shows. For example, `USDC.e` vs `USDC`
---

fix: debt switch symobl icon and max amount

---

src/modules/dashboard/lists/BorrowedPositionsList/BorrowedPositionsListItem.tsx

`reserve.stableBorrowAPY` updates with the rate for new positions, `userReserve.stableBorrowAPY` is for an individual position and should be used on dashboard.
---

fix: use userReserve instead of reserve stableBorrowApy

---

src/components/transactions/DebtSwitch/DebtSwitchModalContent.tsx

- Fixes a bug with checking the available liquidity for a gho debt switch. Previous logic was checking how much is available for the user to mint, but we should only be checking how much is available to mint.
---

fix: gho debt switch liquidity check

---

src/components/transactions/Repay/RepayActions.tsx
src/components/transactions/Supply/SupplyActions.tsx
src/components/transactions/Supply/SupplyModalContent.tsx
src/store/protocolDataSlice.ts

All V3 testnets use a deployment of WETH9Mock which does not implement `permit`/`nonces`. This PR disables the permit approval option for these reserves.
---

chore: disable testnet WrappedBaseAsset permit

---

cypress/support/steps/main.steps.ts
cypress/support/steps/verification.steps.ts
src/helpers/useTransactionHandler.tsx
src/hooks/useTransactionHistory.tsx

fix: typos in comments

---

src/layouts/MainLayout.tsx
src/layouts/TopBarNotify.tsx

chore: market notification [skip cypress]

---

package.json
yarn.lock

update dependency to another outdated version
fixes https://app.aave.com/governance/proposal/?proposalId=375 completely breaking the app
---
Overall dependency hygiene in this project is questionable:
The issue you are currently facing was known and fixed in april.

fix: update dependencies as aave governance is broken

---

cypress/fixtures/assets.json
src/ui-config/reservePatches.ts

- Updates the token display name for USDC to differentiate between bridged and native versions. Some markets have both the native and bridged versions of USDC. This change updates OP and Polygon markets so it's clear which one is being used.
---

fix: native vs. bridged USDC naming

---

cypress/e2e/4-gho-ethereum/gho-basic.ethereum-v3.cy.ts
cypress/e2e/4-gho-ethereum/gho-modal.gho-v3.cy.ts
src/components/transactions/Repay/RepayModal.tsx
src/modules/dashboard/lists/BorrowAssetsList/BorrowAssetsList.tsx
src/utils/getMaxAmountAvailableToBorrow.ts

- Enables repay with collateral for GHO
- Fixes a UI bug where the available amount of GHO to borrow could have been negative

feat: gho repay with collateral

---

.github/workflows/build-test-deploy-dev.yml
.github/workflows/update-prod-staging.yml

remove old IPFS servers

---

package.json
src/architecture/FixedPointDecimal.ts
src/components/transactions/GovDelegation/GovDelegationModalContent.tsx
src/components/transactions/GovVote/GovVoteActions.tsx
src/hooks/governance/useDelegateeData.ts
src/hooks/governance/useGovernanceTokensAndPowers.ts
src/hooks/governance/usePowers.ts
src/hooks/governance/useTokensPower.ts
src/modules/governance/DelegatedInfoPanel.tsx
src/modules/governance/VotingPowerInfoPanel.tsx
src/services/DelegationTokenService.ts
src/ui-config/SharedDependenciesProvider.tsx
src/ui-config/queries.ts
yarn.lock

feat: Fix delegation issues

---

cypress/e2e/4-gho-ethereum/helpers/token.helper.ts
src/modules/dashboard/lists/BorrowAssetsList/BorrowAssetsList.tsx

- Fixes liquidation warning showing incorrectly in the borrow list. Previously was based off of collateral usage, which will trigger warning to show incorrectly for low LTV assets. It's now based on health factor
---

fix: show warning when low FH

---

pages/governance/ipfs-preview.governance.tsx
src/modules/governance/proposal/ProposalOverview.tsx

- Adds in the ipfs preview page. This was lost during the gov v3 refactor.
- Fixes an issue where the raw ipfs link on the proposal details page wasn't working
New page is at `/governance/ipfs-preview/?ipfsHash=0x0...`
Can test this out using some of these ipfs hashes:
```
0x3dffd2f1b7a87a3f44ab31d0da89e5b64a6258468843c4599edd4527a4cd8c3a
0xb87ef765d6082f5ac26466bc730b069c42d4ea9fe130250a26be627ac259d259
0xbaf47f585bee303606be09f9f9c4215875e8ab48df280c5cabebb94d722a5dd2
0xb33d9ebd247cdfb3e2dee839f082a113b74b4c849c90aa6212531741b6c2b82d
0x57dec17b5950c76b33917a2ff61784a85c796c9fc061e91d313b3fc8a23e6ecf
0x6f9c36de2cb41a1fadfe2f679c47eba6ac4c735de8ee12d3fa5b0d2b6fc3e29e
0xa9b79871f27b840c5d04672f5b2ef16c753938cb80c6809087c1a47ad0fa2880 …
```

fix: add in ipfs preview page

---

src/modules/dashboard/lists/BorrowAssetsList/BorrowAssetsListItem.tsx
src/modules/dashboard/lists/BorrowAssetsList/BorrowAssetsListMobileItem.tsx
src/modules/dashboard/lists/BorrowedPositionsList/BorrowedPositionsListItem.tsx
src/modules/dashboard/lists/SuppliedPositionsList/SuppliedPositionsListItem.tsx
src/modules/dashboard/lists/SuppliedPositionsList/SuppliedPositionsListMobileItem.tsx
src/modules/dashboard/lists/SupplyAssetsList/SupplyAssetsListItem.tsx
src/modules/markets/MarketAssetsListItem.tsx
src/modules/markets/MarketAssetsListMobileItem.tsx
src/utils/utils.ts

Superfest incentives on weETH supply have been negociate for the Aave users by ACI x Ether.fi x Conclave
- add Superfest incentive indicator for weETH supply
- show Superfest incentives on Markets panel
---

feat: add Superfest incentive indicator for weETH supply

---

src/store/poolSelectors.ts

- Ensures there is always a default eMode (none) if all reserves have a non-zero eMode category
---

fix: default emode [skip cypress]

---

src/components/transactions/DebtSwitch/DebtSwitchModalDetails.tsx

- When GHO is not a mintable reserve (arbitrum) display the apy the same way as any other reserve.
---

feat: Gho debt swap APY display

---

src/services/UIPoolService.ts

- Use legacy data providers for testnets since they do not have the 3.2 upgrade
---

fix: use legacy providers for testnets

---

src/hooks/useMeritIncentives.ts

…
As some new liquidity mining (LM) programs will need to pass through Merit due to the standard LM workflow not being adapted for their asset decimals, we will very soon require Merit programs that can run in parallel—one program for the supply side and one for the borrow side. This PR addresses that need.
When been implemented these change will be used to launch 3 Base LM programs (#2243)
---

feat: update Merit incentives to support supply and borrow incentive sides at the same time

---

src/ui-config/networksConfig.ts

- Updates pokt urls to latest
---

chore: update pokt urls

---

src/libs/web3-data-provider/WalletConnectConnector.ts

- Adjusts wc config to use default rpc endpoints and added in metadata
---

fix: wc rpc and config [skip cypress]

---

src/layouts/MainLayout.tsx

feat: user feedback [skip cypress]

---

.github/workflows/update-prod-staging.yml
README.md

As we have a feature toggle to switch to testnets we no longer have the need to maintain a separate env. 
Simplifying gh action and updating Readme.

Remove staging deployment

---

src/hooks/useMeritIncentives.ts

Merit campaigns can be temporarily paused. This pull request introduces functionality to quickly disable the incentive box during such pauses.
It's important to note that paused campaigns often indicate that clients are taking some time to reflect before deciding to renew the incentives, rather than always signaling the end of the campaign.
- mask incentive box when the corresponding Merit campaign is temporary paused, preventing the following:
RAS
---

feat: mask Merit campaign when aprs are not found

---

src/libs/web3-data-provider/Web3Provider.tsx

- set account to be in lower case in readonly mode
---

fix: account in readonly [skip cypress]

---

package.json
src/components/incentives/MeritIncentivesTooltipContent.tsx
src/hooks/useMeritIncentives.ts
yarn.lock

- update aave-address-book lib (in order to get the new AUSD token from Avalanche market)
- add a new avalanche-supply-ausd (not lived yet)
- change default forum link for the LM incentives one
You can see the result when the campaign will be lived by mocking API response: 
Put `meritIncentives.actionsAPR[MeritAction.AVALANCHE_SUPPLY_AUSD] = 0.1;` after Line 194 of `useMeritIncentives.ts`
---

✨ Implement new AUSD supply Merit incentives

---

src/ui-config/networksConfig.ts

- Fixes extra slash in explorer link for base_sepolia, bnb, scroll, and zksync
Related to https://github.com/aave/interface/issues/2315
---

Remove unnecessary slash in explorer links [skip cypress]

---

package.json
src/hooks/app-data-provider/useAppDataProvider.tsx
src/hooks/pool/useUserYield.ts
yarn.lock

- Updates utils packages which includes fix properly calculating a users gho debt balance with a discount applied
- Updates reserves in app data provider in the case where the user does have a gho discount so the correct amount can be used throughout the app
- Fixes a bug where the discount rate wasn't being factored into the users weighted average borrow apy displayed
---

fix: gho debt amount

---

src/modules/dashboard/DashboardContentWrapper.tsx

- Adds more consistent layout for view transactions button which looks bugged on dapp browsers 
---

chore: improve css on view transactions button [skip cypress]

---

src/hooks/useZeroLTVBlockingWithdraw.tsx

Fixing an issue reported by an user that blocked him to withdraw while having assets with LTV=0.
Co-Authored with @grothem

fix: allow withdrawals having an ltv=0 asset if total borrows are zero

---

cypress/support/steps/configuration.steps.ts
cypress/support/tools/tenderly.ts

- Changes tenderly fork dependency with virtual testnets (vnet term is used in code)
Tests result is the same as with tenderly forks. I am just not sure if it is expecting.
`yarn dev`
`DOTENV_CONFIG_PATH='.env.local' yarn run test:headless` 
https://app.warp.dev/block/7DcfA8QJeMqf9tbgsCkcTq
---

chore(e2e): migrate from tenderly forks to virtual testnets

---

src/components/primitives/FormattedNumber.tsx

Fix 7 decimals when number is 1
We are currently showing 1.0000000
Let's be consistent and show 1.00 with two decimals.

fix: decimals formatting when number is 1 

---

src/ui-config/reservePatches.ts

Updated USDC reserve name since it's now the native asset on sonic. Contracts will be updated soon, so putting in a patch until they are.

chore: patch sonic usdc [skip cypress]

---

src/hooks/useMeritIncentives.ts

Fixes merit for patched USDC reserve name/symbol

fix: reserve patch name for merit [skip cypress]

---

src/hooks/paraswap/common.ts

Fixing edge case for truncated amounts.
Example:
```     
const bigAmount = "9007199254740992001"; // 2^53 + 1
console.log("Input string:", bigAmount);
console.log("Number(bigAmount):", Number(bigAmount));
console.log("calculateSignedAmount(bigAmount, 0, 0):", calculateSignedAmount(bigAmount, 0, 0));      
Input string:                           9007199254740992001
Number(bigAmount):                      9007199254740992000
calculateSignedAmount(bigAmount, 0, 0): 9007199254740992000
```
Now using BigNumber.
```
without margin
Input string: 9007199254740992001
Number(bigAmount): 9007199254740992000
amountBN 9007199254740992001
marginBN 0
amountWithMargin 9007199254740992001
alculateSignedAmount(bigAmount, 0, 0): 9007199254740992001
with margin
Input string: 9007199254740992001 …
```

fix: truncated paraswap approval amounts[skip cypress]

---

cypress/e2e/2-settings/switch-tabs.cy.ts
src/ui-config/menu-items/index.tsx

- Updated FAQ to aave.com/faq
- Updated docs to aave.com/doc
Modified  `cypress/e2e/2-settings/switch-tabs.cy.ts` and `src/ui-config/menu-items/index.tsx` to match current docs urls
---

fix: update docs urls in the menu

---

src/hooks/useMeritIncentives.ts

Upgrade sgho Merit root to avoid using currently depreciated sktGHO root
I'm in charge of [ACI Merit endpoint](https://apps.aavechan.com/api/merit/aprs) and created this pull request to upgrade the current root key as currently used is deprecated since Umbrella deployment.
---

feat: use new sgho Merit key for former stkgho

---

src/hooks/paraswap/common.ts

- Round up on slippage input amount calcs. This fixes an issue where some swaps could fail due to a 1 wei precision error.
---

fix: slippage input rounding

---

src/hooks/useMerklIncentives.ts

The Merkl API have some issue regarding the info it provides. A fix was needed on order to display the incentives.
Fix:
- eligible token address
- reward token address
Now the incentives are now display.
Note: We're currently talking with Merkl to improve their API (because it's not yet fully optimal)
---

fix: eligible token + reward token

---

src/hooks/useMeritIncentives.ts

Add display of Avalanche supply GHO incentive that will be launched this week in sync with Ava Labs and Tokenlogic
I enforce display of incentive to verify if display is correct.
---

feat: add Masiv Avalanche supply GHO incentive

---

package.json
src/components/primitives/Link.tsx
src/modules/markets/Gho/GhoBanner.tsx
src/modules/markets/MarketAssetsListContainer.tsx

- Solving issue #2573.
- Show GHO in the core markets asset list.
- Update GHO banner link to navigate to the sGHO page (ROUTES.sGHO).
1. To ensure the GHO token is always visible in the Core assets list on the Markets page, I commented out a filter that was previously blocking it.  
Line 57-58: 
```
//* Disabled to always show GHO in the core markets list as per issue #2573
//.filter((res) => (displayGhoBanner ? res !== ghoReserve : true)) 
```
2. Updated the banner link in both mobile and desktop components.
Replaced:
```
href={ROUTES.reserveOverview(reserve?.underlyingAsset || '', currentMarket)}
```
with:
```
href={ROUTES.sGHO}
```
As a result of this change, some props and function calls that were only used to build the old URL are no longer needed:
- Removed the unused `reserve` …

fix: issue#2573:  show GHO in core markets & link banner GHO to sGHO savings.

---

src/components/transactions/Borrow/BorrowActions.tsx
src/components/transactions/DebtSwitch/DebtSwitchActions.tsx
src/components/transactions/Repay/RepayActions.tsx
src/components/transactions/Repay/RepayModalContent.tsx
src/components/transactions/Supply/SupplyActions.tsx
src/components/transactions/Supply/SupplyModalContent.tsx
src/components/transactions/Supply/SupplyWrappedTokenActions.tsx
src/components/transactions/Withdraw/WithdrawActions.tsx
src/components/transactions/Withdraw/WithdrawAndSwitchActions.tsx
src/modules/umbrella/UmbrellaActions.tsx
src/modules/umbrella/UmbrellaModalContent.tsx
src/modules/umbrella/UnstakeModalActions.tsx
src/modules/umbrella/UnstakeModalContent.tsx

chore: tracking txs usd amounts to amplitude

---

src/components/ConnectWalletPaperStaking.tsx

- Solving issue #2578 
- The Gho section is removed when wallet not connected in the Safety Mode page.
- Added `justifyContent: 'center'` to improve the grid’s appearance.
- None
---

fix: gho deleted from safety mode when not connected 

---

src/hooks/pool/useUserYield.ts
src/hooks/useEnhancedUserYield.ts
src/hooks/useMeritIncentives.ts
src/hooks/useUserMeritIncentives.ts
src/modules/dashboard/DashboardTopPanel.tsx

- Adds combined net apy with merit program
---

feat: net apy

---

src/components/primitives/TokenIcon.tsx
src/components/transactions/Switch/SwitchAssetInput.tsx
src/components/transactions/Switch/SwitchModalTxDetails.tsx
src/components/transactions/Switch/SwitchTxSuccessView.tsx

fix: lazy loading icons in firefox

---

pages/api/support-create-ticket.ts

- Deleted the application of labels to new inquiries from the Aave interface to Plain support
---

fix: exclude labels for plain support

---

src/components/transactions/Switch/common.ts

feat: enable main
